### ISSUE TITLE
Question related to normalization

### ISSUE THREAD

**Issue by JoyOtten** [MarcElosua/SPOTlight#10]
I have maybe a very naive question related to the normalization. I realised that for finding FindAllMarkers you actually use normalized scRNA-seq data with SCT. However, later on to deconvolve the spatial data you use the counts data from spatial which is the raw data. Why don't you use over there as well the SCT normalized data? 

Thank you for your help and I really like SPOTlight

**Comment by MarcElosua** [comment]
Hi @JoyOtten 
Thank you very much for using SPOTlight. 
To identify the differentially expressed genes we use SCTransform as it is the recommended workflow in Seurat to normalize the data. SPOTlight in turn uses unit-variance normalization for both the sc and spatial count matrices.
Hope this helps and please don't hesitate to get back to me if you have any other questions.

**Comment by quanc1989** [comment]
Hi @MarcElosua 
I am also confused about a similar question.
I understand that you use SCTransform to follow the recommended workflow to identify DE genes.
However, in the example of deconvolution, you suggest as follows

```
spotlight_ls <- spotlight_deconvolution(se_sc = cortex_sc,
                                        counts_spatial = anterior@assays$Spatial@counts,
                                        clust_vr = "subclass",
                                        cluster_markers = cluster_markers_all,
                                        cl_n = 50,
                                        hvg = 3000,
                                        ntop = NULL,
                                        transf = "uv",
                                        method = "nsNMF",
                                        min_cont = 0.09)
```

You used the assay of 'SCT' (spatial) for the counts_spatial while 'RNA' for the se_sc (I recognized default assay from the documentation for spotlight_deconvolution)? 

As I known, the slot of counts are different between 'SCT' and 'RNA'.   Why don't you use the same assay or I missed something?

**Comment by MarcElosua** [comment]
hi @quanc1989,
As I mentioned in the previous comment SPOTlight uses unit variance normalization to run the model. Regarding the assay of choice to get the DE it is flexible and does not need to be SCT!
Hope this answers your question.
