### ISSUE TITLE
scatter plot circles instead of sctter pie circles

### ISSUE THREAD

**Issue by cathalgking** [MarcElosua/SPOTlight#100]
Would it be possible to plot the output of `plotSpatialScatterpie` as individual scatterplot circles instead of scatterpie circles? For example with geom_point() or some other way. Could I edit the `plotSpatialScatterpie` function to do this? And if so where can I access the code to do so?
Thanks.

**Comment by MarcElosua** [comment]
Hi @cathalgking 

Thank you for using SPOTlight!

Absolutely! The best way to do it is to add the proportions to your object's spot-associated metadata slot - seurat@meta.data or colData(sce). That way you can use their native functions to achieve these plots!
