### ISSUE TITLE
How to plot specific cell type proportions in the newest version of spotlight?

### ISSUE THREAD

**Issue by awesomedeer** [MarcElosua/SPOTlight#103]
Dear @MarcElosua 
From the newest manual I don't see the commands to join decomposition to metadata and plot specific cell type proportions.

Best regards
Song

**Comment by MarcElosua** [comment]
Hi @awesomedeer,

If you're working with a Seurat object it should be the same as before. If working with a Bioconductor data containers you can follow along [here](https://www.bioconductor.org/packages/release/bioc/vignettes/SPOTlight/inst/doc/SPOTlight_kidney.html)

```
plotSpatialScatterpie(
    x = spe,
    y = mat,
    cell_types = colnames(mat),
    img = FALSE,
    scatterpie_alpha = 1,
    pie_scale = 0.4) +
    scale_fill_manual(
        values = pal,
        breaks = names(pal))
```

Where spe is your spatial experiment and mat are your predicted cell type proportions.
