### ISSUE TITLE
downsample_se_obj

### ISSUE THREAD

**Issue by zhangmin513** [MarcElosua/SPOTlight#106]
downsample_se_obj  function can't find

**Comment by MarcElosua** [comment]
Hi @zhangmin513 

This function has been deprecated in the current version of SPOTlight!

**Comment by zhangmin513** [comment]
By the way, if I want to reproduce the experiment in your paper, which version should I use? Additionally, I cannot find a corresponding dataset for the data used in the paper. Could you please indicate which dataset corresponds? I would greatly appreciate it (the experiment cannot be run)
