### ISSUE TITLE
Questions about some details in paper

### ISSUE THREAD

**Issue by NianzhenGu** [MarcElosua/SPOTlight#107]
Hi! I read through the paper and I think it is a very inspiring method. However, I have some questions about your explanation of the SPOTlight algorithm. 

1. I think P is the final matrix we want to calculate. Then how can we use 1-P to initialize the W? Also, will the initial entries of W be 0 or 1? 

> Before running factorization, we initialize each topic, column, of W with the unique marker genes for each cell type with weights 1 – P value.

2. What is the meaning of "the corresponding belongance of each cell for each topic"? How do we know which cell belongs to which topic if the topic has no meaning at the beginning? 

> Each topic of H in SPOTlight is initialized with the corresponding belongance of each cell for each topic, 1 or 0.

3. Here is my understanding of the workflow. I also put the equation of nsNMF and NNLF. Is it correct? For the nsNMF, as matrix S contains a variable theta, I wonder how you decide the value of it. 
<img width="1098" alt="workflow" src="https://github.com/MarcElosua/SPOTlight/assets/145458678/24729de6-c593-42d2-82d3-a8b82eb771c8">

4. For the Jensen-Shannon Divergence (JSD) distance metric used in Performance evaluation, are the P and Q the same as the previous matrix? 

I'm very appreciate it if you could give me some explanations. Thank you very much!

**Comment by MarcElosua** [comment]
Hi @NianzhenGu,

1. I think P is the final matrix we want to calculate. Then how can we use 1-P to initialize the W? Also, will the initial entries of W be 0 or 1?
> In this case P refers to the P-value, see `... weights 1 – P value`. Therefore initial entries of W are 1e-12 or 1 - p-value for that gene in that cell-type associated topic.

2. What is the meaning of "the corresponding belongance of each cell for each topic"? How do we know which cell belongs to which topic if the topic has no meaning at the beginning?
> In this case we want to force NMF to ideally learn a topic that represents a cell type/state. Therefore in the H matrix all the cells that belong to the same cell type have a 1 in the topic associated to that cell type and a 0 in the others

3. I am using the `NMF` and `nnls` package implementation in R. Find [here](https://cran.r-project.org/web/packages/NMF/vignettes/NMF-vignette.pdf) more details  for NMF and [here](https://cran.r-project.org/web/packages/nnls/nnls.pdf) more details for nnls.

4. For the Jensen-Shannon Divergence (JSD) distance metric used in Performance evaluation, are the P and Q the same as the previous matrix?
> In that case P and Q are the matrices with the ground truth and predicted proportions.

Hope this helps!

**Comment by NianzhenGu** [comment]
Thanks for the explanation!
