### ISSUE TITLE
Fixed Matrix version incompatible with SeuratObject

### ISSUE THREAD

**Issue by lardenoije** [MarcElosua/SPOTlight#108]
There was probably a good reason to fix the Matrix package version to 1.6-1.1, however this version appears to be incompatible with the SeuratObject package (version 5.0.1), which requires it to be >= 1.6.3. If I install SPOTlight without that commit (https://github.com/MarcElosua/SPOTlight/tree/0c8a2879fbe1422a1ef5973c20939249ce8f54ca) it appears to work with SeuratObjects without issues.

**Comment by MarcElosua** [comment]
hi @lardenoije Thank you for the heads up!

I was trying to figure out how to fix the discrepancy between Seurat and the Matrix package! Everything should be solved in the `devel` branch and pushed to Bioconductor.
 
 This should work now:
```
install_github("https://github.com/MarcElosua/SPOTlight@devel")
```
