### ISSUE TITLE
How to annotate a spot as a type of cell

### ISSUE THREAD

**Issue by M-jk22** [MarcElosua/SPOTlight#112]
SPOTlight is an excellent tool for annotating spatial transcriptomics data because it provides us with the cellular composition information for each spot. However, if I want to classify each spot into a specific cell type, is there a parameter that can achieve this?

**Comment by MarcElosua** [comment]
hi @M-jk22,

Unfortunately, due to the size of the spots the transcriptome of multiple cells may be simultaneously captured. Assigning each spot to one individual cell type would not be a correct practice in this case.

Hope this helps!
