### ISSUE TITLE
Benchmarking SPOTlight 

### ISSUE THREAD

**Issue by vitkl** [MarcElosua/SPOTlight#12]
Hi @MarcElosua 

As a part of cell2location paper (https://www.biorxiv.org/content/10.1101/2020.11.15.378125v1), we are doing a benchmark of all spatial mapping methods that integrate scRNA & spatial sequencing data. We seem to get the poor performance of SPOTlight on both simulated data (Fig S2, https://www.biorxiv.org/content/biorxiv/early/2020/11/17/2020.11.15.378125/DC1/embed/media-1.pdf?download=true) and real data of both the mouse brain (https://github.com/vitkl/cell2location_paper/blob/master/notebooks/selected_results/benchmarking/mouse_visium_snrna/SPOTlight/plots/figures/spatialall_maps_dotST8059048.pdf) and the human lymph nodes (https://github.com/vitkl/cell2location_paper/blob/master/notebooks/selected_results/benchmarking/lymph_nodes_analysis/SPOTlight/plots/figures/spatialall_maps_dot.png).

I copied over the workflow from your readme and installed the package as instructed. Here are the links to Rmd notebooks (and corresponding *.html report) used for the analysis on mouse brain (https://github.com/vitkl/cell2location_paper/blob/master/notebooks/benchmarking/other_methods/SPOTlight_mouse_brain.Rmd) and human lymph node (https://github.com/vitkl/cell2location_paper/blob/master/notebooks/benchmarking/other_methods/SPOTlight_human_LN.Rmd). I am wondering if you have any suggestions that might explain this. Could I be using a bad combination of hyperparameters?
We do see better results with the lymph node which relies on scRNA rather than snRNA reference dataset and has fewer cell types (34 compared to 59 in the mouse brain). Our working hypothesis is that methods which do not model the gene-specific difference between technologies (SPOTlight, Seurat V3, NNLS) perform worse than cell2location / RCTD / stereoscope when such differences are present in the data.

If you would like to reproduce these results you can find the mouse brain Visium and snRNA-seq as h5ad files as described in this section: https://cell2location.readthedocs.io/en/latest/notebooks/cell2location_short_demo.html#1.-Loading-Visium-data. You can get lymph node Visium data from 10X website and the scRNA-reference dataset we used from https://cell2location.cog.sanger.ac.uk/paper/integrated_lymphoid_organ_scrna/RegressionNBV4Torch_57covariates_73260cells_10237genes/sc.h5ad. You can also find our simulated data here: https://cell2location.cog.sanger.ac.uk/browser.html?shared=paper/lowdens_synthetic_ST_fewcells/.

Would be great if you help to get to the bottom of this.

Thanks a lot,

Vitalii

**Comment by swainasish** [comment]
In the simulated dataset, I can't find the labels of snRNA and ST data, It will be really helpful if you share those also.
