### ISSUE TITLE
train_nmf run time

### ISSUE THREAD

**Issue by stephenwilliams22** [MarcElosua/SPOTlight#14]
I have a single-cell data set that has approximately 50k cells and 20 celltypes. I have downsampled this dataset as per your example in the vignette 
```
se_sc_down <- downsample_se_obj(se_obj = sc_data,
                                clust_vr = "celltypes",
                                cluster_markers = cluster_markers_all,
                                cl_n = 100,
                                hvg = 3000)
```

I'm trying to use SPOTlight for deconvolution but the `train_nmf` function is taking a really long time. I'm about 1 hr in and wondering if this is to be expected or if there is anything that I can do to speed the process up.

Thanks for your help.

**Comment by stephenwilliams22** [comment]
In the end, training the model took `"Time to train NMF model was 52.8mins"`. Have you considered using any of the parallel options available to `nmf`?

**Comment by MarcElosua** [comment]
Hi @stephenwilliams22 ,
Thanks a lot for your feedback, with larger datasets with lots of cell types it does tend to take a while 1-2h. I had not thought about the parallelization of NMF, I will definitely take a look at its implementation!
Thanks again

**Comment by zdebruine** [comment]
You probably may want to look at switching from the `NMF` package to `RcppML::nmf`.  About 60x faster than the NMF package, and natively supports parallelization and sparse matrices.  I am the author, if you have any questions just let me know.  You should fit 50k cells x 20k genes in <1 minute on any good compute node.

Nice algorithm @MarcElosua!  I learned about it during a seminar and was pretty enthused.  Good work.

Also technical Q:  Why are you worrying about seeding?  Generally, random seeding gives the best discoverable solution, and anything short of a random initialization can cause bias or trap in local minima.
