### ISSUE TITLE
Question about the function "test_spot_fun"

### ISSUE THREAD

**Issue by leihouyeung** [MarcElosua/SPOTlight#17]
When I run "test_spot_fun" function, the outputs of cell composition are all zero. What's the matter?

**Comment by weifangliu** [comment]
Did you figure out why this was the case?

**Comment by MarcElosua** [comment]
Hi @weifangliu `test_spot_fun` is no longer supported. Using SPOTlight's latest version you can create synthetic mixtures from a single cell reference using `mockSP()` which returns the proportions in `metadata(sce)`.

**Comment by weifangliu** [comment]
Thank you for the update!
