### ISSUE TITLE
using purrr::map to speed up deconvolution process

### ISSUE THREAD

**Issue by sengao86** [MarcElosua/SPOTlight#18]
Hi,

The deconvolution process is pretty slow, as one spot takes roughly 10~30s. For a large dataset consisting of thousands of spots, the whole deconvolution process consumes more than 5 hours, making it hard for the user to tune the parameter quickly based on the results. Part of this problem is that spotlight deconvolute spots one by one. Any thoughts to append parallel computing in the spotlight to fuel the speed?

Plus, very nice program and congratulations on the NAR publication!

@QqQss

**Comment by MarcElosua** [comment]
Hi @sengao86,

Thanks a lot for using SPOTlight and taking the time to go over it and provide feedback!
As far as I'm aware the current bottle-neck is the Matrix Factorization, I am currently exploring ways to parallelize that step to significantly increase the speed. The option I'm looking into right now is using `parallel-NMF` from the NMF package but I'm open to suggestions.

I will keep you updated as I make further improvements to enhance the speed!
