### ISSUE TITLE
a new error encountered

### ISSUE THREAD

**Issue by sengao86** [MarcElosua/SPOTlight#19]
Hi,

I encountered an error when run deconvolution:

Error in nnls::nnls(A = W, b = count_mtrx[, i]): NA/NaN/Inf in foreign function call (arg 5)
Traceback:

1. spotlight_deconvolution(se_sc = qin, counts_spatial = st_data[[1]]@assays$Spatial@counts[, 
 .     1:2], clust_vr = "majorCluster", cluster_markers = cell_type_markers, 
 .     cl_n = 10, hvg = 300, ntop = NULL, transf = "uv", method = "nsNMF", 
 .     min_cont = 0)
2. mixture_deconvolution_nmf(nmf_mod = nmf_mod_ls[[1]], mixture_transcriptome = counts_spatial, 
 .     transf = transf, reference_profiles = ct_topic_profiles, 
 .     min_cont = min_cont)
3. predict_spatial_mixtures_nmf(nmf_mod = nmf_mod, mixture_transcriptome = mixture_transcriptome, 
 .     transf = transf)
4. nnls::nnls(A = W, b = count_mtrx[, i])

No idea why this happened.

Hope get some help, thanks!

**Comment by MarcElosua** [comment]
Hi @sengao86 ,
I see you have closed this issue, hope you were able to solve the error!
Please let me know if you need any additional assistance,
Marc

**Comment by sengao86** [comment]
Hi @MarcElosua MarcElosua,

Yes the problem solved. Thanks!
