### ISSUE TITLE
spotlight_deconvolution error

### ISSUE THREAD

**Issue by sarahcooper22** [MarcElosua/SPOTlight#23]
Hello, I am trying to run my data through the same code as is provided for the tutorial and keep running into the issue below. The tutorial code with the provided brain data ran perfectly fine, but I am not having any luck on my own work. If you have any suggestions, that would be greatly appreciated! Thanks!
![SPOTlight_error](https://user-images.githubusercontent.com/60239141/118866777-925fe100-b89f-11eb-84f5-e6992a00eaf5.png)

**Comment by MarcElosua** [comment]
Hi @sarahcooper22 ,
I suspect this may happen because there are genes that have 0 UMI counts for all the cells, could you try removing those genes and re-running it?
Hope this helps!

**Comment by sarahcooper22** [comment]
Thank you for the prompt reply! I will give that a try, thank you for your help.
