### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by Roopali24** [MarcElosua/SPOTlight#24]
Hi, I am having trouble installing SPOTlight. When I run the command:

```
devtools::install_git("https://github.com/MarcElosua/SPOTlight")
```
I get the following error:
Downloading GitHub repo satijalab/seurat@spatial
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/satijalab/seurat/tarball/spatial'
✓  checking for file ‘/private/var/folders/nt/fw_0vt6n647_d_zvvngdkj_c0000gn/T/Rtmpj3iotG/file13b7e5725b352/DESCRIPTION’ ...
─  preparing ‘SPOTlight’: (622ms)
✓  checking DESCRIPTION meta-information
   Warning: /private/var/folders/nt/fw_0vt6n647_d_zvvngdkj_c0000gn/T/RtmprOI0PX/Rbuild13c2121ab3e7/SPOTlight/man/mixture_deconvolution_nmf.Rd:26: unexpected section header '\value'
   Warning: /private/var/folders/nt/fw_0vt6n647_d_zvvngdkj_c0000gn/T/RtmprOI0PX/Rbuild13c2121ab3e7/SPOTlight/man/mixture_deconvolution_nmf.Rd:29: unexpected section header '\description'
   Warning: /private/var/folders/nt/fw_0vt6n647_d_zvvngdkj_c0000gn/T/RtmprOI0PX/Rbuild13c2121ab3e7/SPOTlight/man/mixture_deconvolution_nmf.Rd:32: unexpected section header '\examples'
      Warning: /private/var/folders/nt/fw_0vt6n647_d_zvvngdkj_c0000gn/T/RtmprOI0PX/Rbuild13c2121ab3e7/SPOTlight/man/spotlight_deconvolution.Rd:56: unexpected END_OF_INPUT '
   '
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'SPOTlight/inst/allen_cortex_dwn.rds'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'SPOTlight/inst/markers_anterior.RDS'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'SPOTlight/inst/spotlight_ls_anterior.RDS'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'SPOTlight/sample_data/allen_cortex_dwn.rds'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'SPOTlight/sample_data/markers_anterior.RDS'  WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'SPOTlight/sample_data/spotlight_ls_anterior.RDS'
─  building 'SPOTlight_0.1.7.tar.gz'
   
* installing *source* package ‘SPOTlight’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
Error : (converted from warning) /private/var/folders/nt/fw_0vt6n647_d_zvvngdkj_c0000gn/T/RtmplKXRp9/R.INSTALL13c2e267f523e/SPOTlight/man/mixture_deconvolution_nmf.Rd:26: unexpected section header '\value'
ERROR: installing Rd objects failed for package ‘SPOTlight’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/SPOTlight’
Error: Failed to install 'unknown package' from Git:
  (converted from warning) installation of package ‘/var/folders/nt/fw_0vt6n647_d_zvvngdkj_c0000gn/T//Rtmpj3iotG/file13b7e6046a5bd/SPOTlight_0.1.7.tar.gz’ had non-zero exit status

Please help. Is there a dependency that I am missing?

**Comment by NKalavros** [comment]
I've encountered this error too in R 4.0.1.

It is some weird code in the functions' manuals. I've been able to successfully install the package by having R ignore those warnings. You can do this using the following snippet:

```Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")```

And confirm that is was set using:

```Sys.getenv(x = "R_REMOTES_NO_ERRORS_FROM_WARNINGS")```

before running:

```
devtools::install_github("https://github.com/MarcElosua/SPOTlight",
                           force = TRUE)
```

Weirdly, this does not occur in the devel branch.

It's also a very makeshift solution and I don't suggest using it in any other case.

**Comment by Roopali24** [comment]
Thank you so much! This worked for me. :)

**Comment by MarcElosua** [comment]
Thanks so much @Roopali24 for reporting this issue and @NKalavros for the solution,
I have looked into it and it was due to a % being in the argument description of the function which then messed up the .rd files.
This should be fixed now in the master branch!

Thanks for your interest in SPOTlight
