### ISSUE TITLE
what is the meaning of  important gene for each topic ?

### ISSUE THREAD

**Issue by mengchengyao** [MarcElosua/SPOTlight#28]
Hi,
    Thank you for your great tool.This is really helpful. I have been  with the value of important gene for each topic, what is meaning for high value and low value?
![image](https://user-images.githubusercontent.com/46958122/127589809-2c22f3f6-5f94-497b-aaa3-5bf64f998416.png)

**Comment by MarcElosua** [comment]
hi @semir2 
Thanks for your interest in SPOTlight!
These are the values learned by the NMF basis matrix. They have no direct interpretation as stand alone numbers and should be looked in the context of each topic.
The general idea of the basis matrix is that each topic learns which genes are important for its associated cell type. Therefore, larger values indicate a higher importance of that gene when defining the topic, This is particularly useful when trying to understand which genes are driving each topic and ultimately the spot decomposition,

Hope this helps,
Marc

**Comment by mengchengyao** [comment]
Hi @MarcElosua ,thanks for your reply, it helps me a lot.

Best wishes
