### ISSUE TITLE
support for SingleCellExperiment or just count matrices?

### ISSUE THREAD

**Issue by giovp** [MarcElosua/SPOTlight#3]
Hi,

thank you for developing this interesting package. 
I was wondering whether it would be possible to add support to SingleCellExperiment for the `sc_count` or just count matrices (if that's the case, then it would be nice allowing the various markers etc. arguments to just accepts e.g. vectors).

Thank you!

**Comment by MarcElosua** [comment]
Thank you very much for your comment!
I will definitely take a look into it and adapt it as much as possible to increase the flexibility and let you know here.

**Comment by MarcElosua** [comment]
Ongoing work at branch - *devel_cmtrx*. It should be functional but need to finish up running some tests...

**Comment by Roopali24** [comment]
Hi,

If we have count data (X) with rows as genes and columns as locations for spatial data, can we just convert it to the  desired format using:

```
sp_seu <- CreateSeuratObject(counts = X)
```

Similarly for single cell data, we can use:

```
sc_seu <- CreateSeuratObject(counts = sc_count)
sc_seu <- AddMetaData(
  object = sc_seu,
  metadata = sc_label$celltype,
  col.name = 'cell_type'
)
```
where sc_count has the gene expression with rows as genes and columns as cells, sc_label$celltype contains the annotations for these cells.

Then can we run our code as such:

```
Seurat::Idents(object = sc_seu) <- sc_seu@meta.data$cell_type

cluster_markers_all <- Seurat::FindAllMarkers(object = sc_seu, 
                                              assay = "RNA",
                                              slot = "data",
                                              verbose = TRUE, 
                                              only.pos = TRUE)


spotlight_ls <- spotlight_deconvolution(se_sc = sc_seu,
                                        counts_spatial = sp_seu@assays$RNA@counts,
                                        clust_vr = "cell_type",
                                        cluster_markers = cluster_markers_all,
                                        cl_n = 100, # 100 by default
                                        hvg = 3000,
                                        ntop = NULL,
                                        transf = "uv",
                                        method = "nsNMF",
                                        min_cont = 0.1)
```

Does this seem right?

**Comment by MarcElosua** [comment]
hi @Roopali24 ,
In your case with the spatial data you can directly pass the count (X) matrix, no need to convert it to a Seurat object. 

```
spotlight_ls <- spotlight_deconvolution(se_sc = sc_seu,
                                        counts_spatial = counts_X, # Count matrix
                                        clust_vr = "cell_type",
                                        cluster_markers = cluster_markers_all,
                                        cl_n = 100, # 100 by default
                                        hvg = 3000,
                                        ntop = NULL,
                                        transf = "uv",
                                        method = "nsNMF",
                                        min_cont = 0)
```

**Comment by Roopali24** [comment]
Thank you. Everything else seems okay?

**Comment by MarcElosua** [comment]
There are some parameters that can be tuned depending on the complexity of your dataset but as a first approach it looks good!

**Comment by Roopali24** [comment]
Okay. Thank you. I'll look into the other parameters.
