### ISSUE TITLE
Question for multiple ST samples

### ISSUE THREAD

**Issue by astrid12345** [MarcElosua/SPOTlight#32]
Dear MarcElosua,

I have multiple ST samples in one experiment. I am wondering, once my NMF model is trained ( nmf_mod_ls in the tutorial), can I use one NMF model for multiple ST samples to deconvolve the mixture/spots? 

What conditions do the samples need to satisfy before I could try using the same NMF model? Or would you recommend always training the NMF again for each sample?

Thanks,

**Comment by astrid12345** [comment]
thanks! i already ended up running each NMF for each replicate!

**Comment by MarcElosua** [comment]
Hi @astrid12345 

This may come a bit late but an approach I use sometimes to run SPOTlight on multiple samples is to merge them all in 1 Seurat object and run it on it. This allows you to train the model once only and reduces the computational bottleneck an also ensures all the samples have the same model trained on them. Obviously this should be done if the samples are similar between them!

Thanks again for your interest and hope this helps in future analysis!

**Comment by astrid12345** [comment]
Ah thanks, i didn't think of that! Yes, this could really help in the future. I wanted to share how much I appreciate SPOTlight: your workflow is elegant, simple and computationally efficient. Thank you for this wonderful contribution!
