### ISSUE TITLE
applying SPOTLight on multiple ST samples

### ISSUE THREAD

**Issue by skim245** [MarcElosua/SPOTlight#33]
@MarcElosua thank you for developing a great "Deconvolution" tool for spatial transcriptomics 
I have a follow-up question on #32.
I also have multiple ST samples in seurat object and run the SPOTLight in a merged format and would like to visualize individual samples and would like to know if there is an easy way to split the visualization based on sample names/replicates. 

In addition, I would also like to add the celltype names in the "metadata" as a "factor" with predicted celltype names in a level instead of individual celltype names in a "double" format. 

Thanks!

**Comment by MarcElosua** [comment]
Hi @skim245,

To visualize individual samples I recommend iterating  over the sample names and apply the visualization function of interest to a subset of the Seurat object containing the data for that slide. 

As for your second issue, I don't understand what you mean. Ultimately SPOTlight returns a `spot x cell type` matrix where the values are doubles. I would need a bit more context to understand what you're trying to do, let me know if I can help.

Marc
