### ISSUE TITLE
Spatial_scatterpie mutate() error

### ISSUE THREAD

**Issue by WesDe** [MarcElosua/SPOTlight#36]
Hi ! 

I followed your tutorial with my own data but when I came to the part to plot the scatterpie with specific cell type of interest an error rise about mutate:

> <error/dplyr:::mutate_error>
> Problem with `mutate()` column `rsum`.
> ℹ `rsum = base::rowSums(.[, cell_types_interest, drop = FALSE])`.
> ✖ undefined columns selected
> Backtrace:
>   1. ├─SPOTlight::spatial_scatterpie(...)
>   2. │ └─`%>%`(...)
>   3. ├─tibble::column_to_rownames(., "barcodeID")
>   4. │ ├─base::stopifnot(is.data.frame(.data))
>   5. │ └─base::is.data.frame(.data)
>   6. ├─dplyr::left_join(...)
>   7. ├─dplyr::select(., "barcodeID")
>   8. ├─dplyr::filter(., rsum != 0)
>   9. ├─dplyr::mutate(...)
>  10. ├─dplyr:::mutate.data.frame(...)
>  11. │ └─dplyr:::mutate_cols(.data, ..., caller_env = caller_env())
>  12. │   ├─base::withCallingHandlers(...)
>  13. │   └─mask$eval_all_mutate(quo)
>  14. ├─base::rowSums(.[, cell_types_interest, drop = FALSE])
>  15. │ └─base::is.data.frame(x)
>  16. ├─.[, cell_types_interest, drop = FALSE]
>  17. ├─base::`[.data.frame`(., , cell_types_interest, drop = FALSE)
>  18. │ └─base::stop("undefined columns selected")
>  19. └─base::.handleSimpleError(...)
>  20.   └─dplyr:::h(simpleError(msg, call))
> <error/simpleError>
> undefined columns selected

Here my sessionInfo if it helps:

> R version 4.0.5 (2021-03-31)
>   Platform: x86_64-conda-linux-gnu (64-bit)
>   Running under: CentOS Linux 7 (Core)
>   
>   Matrix products: default
>   BLAS/LAPACK: /CONDAS/users/delage-w/r_work/lib/libopenblasp-r0.3.15.so
>   
>   locale:
>    [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>    [3] LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_US.UTF-8    
>    [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8   
>    [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
>    [9] LC_ADDRESS=C               LC_TELEPHONE=C            
>   [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
>   
>   attached base packages:
>   [1] grid      parallel  stats     graphics  grDevices utils     datasets 
>   [8] methods   base     
>   
>   other attached packages:
>    [1] jpeg_0.1-9            png_0.1-7             imager_0.42.10       
>    [4] magrittr_2.0.1        cowplot_1.1.1         tidyr_1.1.4          
>    [7] tibble_3.1.6          stringr_1.4.0         Biobase_2.52.0       
>   [10] BiocGenerics_0.38.0   ggcorrplot_0.1.3      RColorBrewer_1.1-2   
>   [13] igraph_1.2.8          SPOTlight_0.1.7       gt_0.3.1             
>   [16] data.table_1.14.2     Matrix_1.3-4          dplyr_1.0.7          
>   [19] patchwork_1.1.1       ggplot2_3.3.5         SeuratDisk_0.0.0.9019
>   [22] SeuratData_0.2.1      SeuratObject_4.0.3    Seurat_4.0.5.9003    
>   
>   loaded via a namespace (and not attached):
>     [1] Rtsne_0.15            colorspace_2.0-2      deldir_1.0-6         
>     [4] ellipsis_0.3.2        ggridges_0.5.3        rprojroot_2.0.2      
>     [7] spatstat.data_2.1-0   farver_2.1.0          leiden_0.3.9         
>    [10] listenv_0.8.0         ggrepel_0.9.1         bit64_4.0.5          
>    [13] scatterpie_0.1.7      RSpectra_0.16-0       fansi_0.5.0          
>    [16] codetools_0.2-18      splines_4.0.5         doParallel_1.0.16    
>    [19] readbitmap_0.1.5      polyclip_1.10-0       jsonlite_1.7.2       
>    [22] gridBase_0.4-7        ica_1.0-2             cluster_2.1.2        
>    [25] uwot_0.1.10           ggforce_0.3.3         shiny_1.7.1          
>    [28] sctransform_0.3.2     spatstat.sparse_2.0-0 compiler_4.0.5       
>    [31] httr_1.4.2            bmp_0.3               assertthat_0.2.1     
>    [34] fastmap_1.1.0         lazyeval_0.2.2        cli_3.1.0            
>    [37] tweenr_1.0.2          later_1.3.0           htmltools_0.5.2      
>    [40] tools_4.0.5           gtable_0.3.0          glue_1.5.0           
>    [43] RANN_2.6.1            reshape2_1.4.4        rappdirs_0.3.3       
>    [46] Rcpp_1.0.7            scattermore_0.7       NMF_0.23.0           
>    [49] vctrs_0.3.8           nlme_3.1-153          iterators_1.0.13     
>    [52] lmtest_0.9-39         globals_0.14.0        mime_0.12            
>    [55] miniUI_0.1.1.1        lifecycle_1.0.1       irlba_2.3.3          
>    [58] rngtools_1.5.2        goftest_1.2-3         future_1.23.0        
>    [61] MASS_7.3-54           zoo_1.8-9             scales_1.1.1         
>    [64] spatstat.core_2.3-1   promises_1.2.0.1      spatstat.utils_2.2-0 
>    [67] reticulate_1.22       pbapply_1.5-0         gridExtra_2.3        
>    [70] ggfun_0.0.4           pkgmaker_0.32.2       rpart_4.1-15         
>    [73] stringi_1.7.5         foreach_1.5.1         tiff_0.1-10          
>    [76] rlang_0.4.12          pkgconfig_2.0.3       matrixStats_0.61.0   
>    [79] lattice_0.20-45       ROCR_1.0-11           purrr_0.3.4          
>    [82] tensor_1.5            labeling_0.4.2        htmlwidgets_1.5.4    
>    [85] bit_4.0.4             tidyselect_1.1.1      here_1.0.1           
>    [88] parallelly_1.28.1     RcppAnnoy_0.0.19      plyr_1.8.6           
>    [91] R6_2.5.1              generics_0.1.1        DBI_1.1.1            
>    [94] pillar_1.6.4          withr_2.4.2           mgcv_1.8-38          
>    [97] fitdistrplus_1.1-6    survival_3.2-13       abind_1.4-5          
>   [100] future.apply_1.8.1    crayon_1.4.2          hdf5r_1.3.4          
>   [103] KernSmooth_2.23-20    utf8_1.2.2            spatstat.geom_2.3-0  
>   [106] plotly_4.10.0         digest_0.6.28         xtable_1.8-4         
>   [109] httpuv_1.6.3          munsell_0.5.0         registry_0.5-1       
>   [112] viridisLite_0.4.0 

Any idea ? I see that the issue comes from dplyr but I am unable to figure out how to resolve it.
Best,
WesDe

**Comment by MarcElosua** [comment]
Hi @WesDe 

Are the `cell_types_interest` names identical to those in the metadata?

**Comment by WesDe** [comment]
Hi @MarcElosua, 

You are right I don't know how but special characters such as space have been changed to dot in cell_type_all.

Best,
WesDe
