### ISSUE TITLE
spatial_scatterplot spots not aligned with image

### ISSUE THREAD

**Issue by morganee261** [MarcElosua/SPOTlight#38]
Hello, 
I am trying to plot the spot composition using your spatial_scatterplot function. It works great for 2 out 4 of my samples. But for the other ones the spots are misaligned form the sample image even though I use the exact same code. Here it is :
SPOTlight::spatial_scatterpie(se_obj=C140,
                              cell_types_all = cell_types_all_C140,
                              img_path = "/home/Morgane/Visium/Human/C363-c12/outs/spatial/tissue_lowres_image.png",
                              slice=C140,
                              pie_scale = 0.8)

Would you be able to help with that please?
thanks for this great tool.
Morgane

**Comment by MarcElosua** [comment]
I believe I answered your question here - https://github.com/MarcElosua/SPOTlight/issues/9
