### ISSUE TITLE
spotlight_deconvolution function error

### ISSUE THREAD

**Issue by ccomo0730** [MarcElosua/SPOTlight#39]
Hello, I am currently running the SPOTlight package and attempting the spotlight decomposition portion of the. code on my reference scRNAseq data. The code I am running is below:
#Spotlight decomposition
set.seed(123)
spotlight_ls <-spotlight_deconvolution(
se_sc = E14_sc,
counts_spatial = anterior@assays$RNA@counts,
clust_vr = "subclass", # Variable in sc_seu containing the cell-type annotation
cluster_markers = cluster_markers_all, # Dataframe with the marker genes
cl_n = 100, # number of cells per cell type to use
hvg = 3000, # Number of HVG to use
ntop = NULL, # How many of the marker genes to use (by default all)
transf = "uv", # Perform unit-variance scaling per cell and spot prior to factorzation and NLS
method = "nsNMF", # Factorization method
min_cont = 0 # Remove those cells contributing to a spot below a certain threshold
)

When I run this code, I get the following error: Error in spotlight_deconvolution(se_sc = E14_sc, counts_spatial = anterior@assays$RNA@counts, :
could not find function "spotlight_deconvolution"

**Comment by MarcElosua** [comment]
hi @ccomo0730 

Thanks a lot for your interest in SPOTlight!

We are currently on the process of submitting SPOTlight to bioconductor and there have been some styling changes on this branch compared to previous releases. If you want to use the version we are currently submitting feel free to look at the updated vignette [here](https://github.com/MarcElosua/SPOTlight/blob/main/vignettes/SPOTlight_kidney.Rmd).

If you want to keep using the previous versions, you can still find it in the [spotlight-0.1.7](https://github.com/MarcElosua/SPOTlight/tree/spotlight-0.1.7) branch and follow the previous [vignette](https://marcelosua.github.io/SPOTlight/). 

Hope this helps,
Marc

**Comment by ccomo0730** [comment]
Hi Marc,
Thank you for your help! Unfortunately I am still having the same error. I am using the previous version vignette with the previous version code.

**Comment by MarcElosua** [comment]
Have you installed the SPOTlight like this?
```
devtools::install_github("https://github.com/MarcElosua/SPOTlight", ref = "spotlight-0.1.7")
```

**Comment by ccomo0730** [comment]
Hi Marc,

I tried removing the package and reinstalling it with the code you provided, but I am still having the same issue. I can see that this function is listed under the package information, so I am not sure why I am still receiving the error!

Thanks,


Christina Como
PhD Candidate
Neuroscience Program, Siegenthaler Lab
University of Colorado Anschutz Medical Campus
E: ***@***.******@***.***>
Pronouns: she/her/hers

[CU Anschutz Website]<https://www.cuanschutz.edu/>


________________________________

**Comment by ccomo0730** [comment]
Hi Marc, after using the code you provided and restarting my R session it worked! Thank you!


Christina Como
PhD Candidate
Neuroscience Program, Siegenthaler Lab
University of Colorado Anschutz Medical Campus
E: ***@***.******@***.***>
Pronouns: she/her/hers

[CU Anschutz Website]<https://www.cuanschutz.edu/>


________________________________
