### ISSUE TITLE
Interpretation heatmap cell interactions

### ISSUE THREAD

**Issue by astrid12345** [MarcElosua/SPOTlight#42]
Dear MarcElosua, 
thank you for this great tool! I really like the plot where cell-cell interactions are visualized in a heatmap, it is visually very intuitive. I understand the proportion is based on the count of spots where a particular combination of 2 celltypes are present, but I’m unsure how this proportion is calculated exactly. 
![CWM](https://user-images.githubusercontent.com/11950358/153383521-7f0ef25d-6216-40e9-986e-4fa1b471876b.png)

I’m interested in the specifics, because I would like to combine multiple white matter brain samples into one heatmap. My questions are:
1) Is the proportion normalized for the total abundance of each cell type? It seems the more abundant cell types in tissue (oligodendrocytes) dominate the plot. How do you define the proportion here?
2) How do I interpret the words “From” and “To” . From the graph I understand it is an undirected graph

**Comment by astrid12345** [comment]
Dear MarcElosua,

I played around using your source code, and I tried out this normalization giving an "undirected" heatmap. For me, the plot now fits better what I know from literature is occurring in my data, but I could be completely misunderstanding your system. What do you think? Do you think this normalization method is suitable?

```
library(matrixStats)

my_count_interaction <- function(x, min_prop) {
  # for each pair of groups count how many
  # samples have value above 'min_prop'
  x <- x > min_prop
  ij <- combn(colnames(x), 2)
  y <- apply(ij, 2, function(.) sum(rowAlls(x[, ., drop = FALSE])))
  
  # construct 'data.frame'
  df <- data.frame(t(ij), y)
  names(df) <- c("from", "to", "n")
  return(df)
}
## my own test

## simulated data 
decon_matrix <- replicate(8, rnorm(100, runif(1, -1, 1)))
decon_matrix <- as.matrix(decon_matrix)

# get interactions table
x = decon_matrix
if (is.null(colnames(x))) {
  colnames(x) <- seq_len(ncol(x))
}
df <- my_count_interaction(x, min_prop = 0)

y <- colnames(x)
df$i <- factor(df$from, y)
df$j <- factor(df$to, rev(y))

# compute proportion of samples that have all groups
t <- colSums(x > 0)
i <- match(df$from, y)
j <- match(df$to, y)
df$ti <- t[i]
df$tj <- t[j]
df$jaccard <- df$n / (df$ti + df$tj - df$n) # I found this index working better for my data.

ggplot(df) +
  geom_tile(aes_string("i", "j", fill = "jaccard")) +
  scale_fill_gradientn(colours = heatmap_colors, limits = c(0,1)) +
  scale_y_discrete(limits = function(.) rev(.)) +
  coord_fixed(expand = FALSE) +
  labs(x = "", y = "", fill = "Jaccard index") +
  theme_linedraw() +
  theme(
    panel.grid = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1))
```

**Comment by MarcElosua** [comment]
Hi @astrid12345

Thank you so much for your interest in SPOTlight and apologies for the delay in answering.
Thank you for suggesting the use of the Jaccard index, we will definitely add it in the next iteration of SPOTligt. 
here goes my explanation of how to interpret the interaction plot:

As per your previous comment here is the explanation, as an example, if we have: 
```
# 3.000 total spots,
# 2.000 contain Oligodendrocytes,
oligo <- 2000
# 100 contain T-cells
tcell <- 100
# t cells and Oligodendrocytes overlap in 75 spots
overlap <- 95

# If we look at the plot from T-cells to Oligodendrocytes we are checking in how many of the spots that contain T cells do we also observe Oligodendrocytes.
overlap / tcell

# Viceversa it would be
overalp / oligo
```

By doing the above we get the non symmetric matrix since we want to account for cell types that can be very abundant.

Again apologies for the delay in answering and thanks a lot for the jaccard index suggestion!
Marc
