### ISSUE TITLE
A typo in updated vignette

### ISSUE THREAD

**Issue by rocketeer1998** [MarcElosua/SPOTlight#43]
Hi there. Maybe there is a typo in the updated vignette. In line 237, `n_cells <- 2` should be modified to `n_cells <- 20` which means downsample to at most 20 per identity. Am I right?

**Comment by MarcElosua** [comment]
Yup, thanks for spotting that! It should be 20 for the vignette. In practice I would set it around 75-100  cells per cell type to make sure `SPOTlight` has enough cells to learn the cell type signature.
