### ISSUE TITLE
Insufficient number of features shared between single-cell and mixture dataset.

### ISSUE THREAD

**Issue by rocketeer1998** [MarcElosua/SPOTlight#44]
Hi there. When I run `SPOTlight()`, there is an error that says `Insufficient number of features shared between single-cell and mixture dataset.`. What's the meaning and how can I fix it? Thanks a lot!

I'm annotating a Visium FFPE data using a reference scRNA-seq data. I wonder whether the inconsistency between the total number of genes detected in Visium and scRNA-seq leads to the above error?

**Comment by MarcElosua** [comment]
Hi @rocketeer1998 ,

Most likely there isn't enough overlap between the gene names between the SC and ST data.
Can you try running:

`intersect(rownames(sc), rownames(st))` and see how many features are shared.

**Comment by rocketeer1998** [comment]
Thanks for your reply, Marc! There are 2905 genes after trying `intersect(rownames(sc), rownames(st))`.
I have to add that my spatial data is obtained from Visium FFPE experiment, which means that the total amount of genes detected is less than that of normal Visium experiment(for fresh frozen tissue). Should we take this factor into account?

**Comment by MarcElosua** [comment]
The FFPE sample could definitely influence the quality of the data. Can you check how many variable features from the sc are intersecting with the st?

**Comment by rocketeer1998** [comment]
> The FFPE sample could definitely influence the quality of the data. Can you check how many variable features from the sc are intersecting with the st?

There are 1004 variable features from the sc intersecting with the ST.

**Comment by MarcElosua** [comment]
Can you try plugging in these features to the parameter `hvg` from `SPOTlight` function?

**Comment by rocketeer1998** [comment]
> 

I'm not quite sure I follow. What's the meaning of `hvg` in `SPOTlight `and what should we set the `hvg `to?

In my opinion, I reckon this error is caused by the fact that the genes in `mgs_df ` for which are used in determining cell types are not wholly present in my spatial data.  Is it right?

**Comment by rocketeer1998** [comment]
> Can you try plugging in these features to the parameter `hvg` from `SPOTlight` function?

I'm not quite sure I follow. What's the meaning of `hvg `in SPOTlight and what should we set the `hvg `to?

In my opinion, I reckon this error is caused by the fact that the genes in `mgs_df `for which are used in determining cell types are not wholly present in my spatial data. Is it right?

**Comment by rocketeer1998** [comment]
For convenience, below is my code. 

``` r

library(Seurat)
library(SeuratObject)
library(Matrix)
library(dplyr)
library(ggplot2)
library(patchwork)
library(cowplot)
library(hdf5r)
library(SPOTlight)
library(SingleCellExperiment)
library(SpatialExperiment)
library(scater)
library(scran)

setwd("F:/VisiumFFPE_1229/4.R_Scripts/")

# Part1: Visium data
merge.Visium <- readRDS("./0214_Monocle3/merge_SeuratObject")
merge.Visium <- RenameAssays(merge.Visium, integrated = "RNA")
#> Renaming default assay from integrated to RNA
#> Warning: Cannot add objects with duplicate keys (offending key: integrated_)
#> setting key to original value 'rna_'
merge.Visium
#> An object of class Seurat 
#> 39469 features across 10101 samples within 3 assays 
#> Active assay: RNA (3000 features, 3000 variable features)
#>  2 other assays present: Spatial, SCT
#>  2 dimensional reductions calculated: pca, umap

# Part2:scRNA-seq data
merge.sc <- readRDS("./merge.sc")
DefaultAssay(merge.sc) <- "RNA"
merge.sce <- as.SingleCellExperiment(merge.sc)
merge.sce
#> class: SingleCellExperiment 
#> dim: 33694 11783 
#> metadata(0):
#> assays(2): counts logcounts
#> rownames(33694): RP11-34P13.3 FAM138A ... AC213203.1 FAM231B
#> rowData names(0):
#> colnames(11783): AAACCCAAGACGGAAA-1_1 AAACCCAAGCATGCAG-1_1 ...
#>   TTTGTTGTCCCTCATG-1_2 TTTGTTGTCTGGCTGG-1_2
#> colData names(8): orig.ident nCount_RNA ... SCINA ident
#> reducedDimNames(0):
#> mainExpName: RNA
#> altExpNames(1): integrated

# Part3:Preprocessing, HVG, marker gene selection
# Normalization
merge.sce <- logNormCounts(merge.sce)

# HVG
deg <- modelGeneVar(merge.sce) 
#plot(deg$mean, deg$total, xlab = "Mean log-expression", ylab = "Variance")
#curve(metadata(deg)$trend(x), col = "blue", add = T)
hvg <- getTopHVGs(deg, n = 3000)

# find the marker genes for each cell type
colLabels(merge.sce) <- colData(merge.sce)$SCINA 
# Get vector indicating which genes are neither ribosomal or mitochondrial
genes <- !grepl(pattern = "^Rp[l|s]|Mt", x = rownames(merge.sce))
# Compute marker genes
mgs <- scoreMarkers(merge.sce, subset.row = genes) 
# keep only those genes that are relevant for each cell identity
mgs_fil <- lapply(names(mgs), function(i) {
  x <- mgs[[i]]
  #keep the marker gene with AUC>0.8
  x <- x[x$mean.AUC > 0.7,]
  #sort AUC in a decreasing manner
  x <- x[order(x$mean.AUC, decreasing = T),]
  #Add gene and cluster id to the dataframe
  x$gene <- rownames(x)
  x$cluster <- i
  data.frame(x)
})
mgs_df <- do.call(rbind, mgs_fil)

#Skip downsampling

# Part4:SPOTlight
res <- SPOTlight(
  x = merge.sce,
  y = merge.Visium,
  groups = merge.sce$labels,
  mgs = mgs_df,
  hvg = hvg,
  weight_id = "mean.AUC",
  group_id = "cluster",
  gene_id = "gene")#1min
#> Error in .filter(x[mod_genes, ], y[mod_genes, ]): Insufficient number of features shared between single-cell and mixture dataset.
# Extract deconvolution matrix
head(mat <- res$mat)[, seq_len(3)]
#> Error in h(simpleError(msg, call)): 在为'head'函数选择方法时评估'x'参数出了错: 找不到对象'res'
# Extract NMF model fit
mod <- res$NMF
#> Error in eval(expr, envir, enclos): 找不到对象'res'
```

<sup>Created on 2022-03-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by MarcElosua** [comment]
Thank you so much for sharing the code, this will make it much easier to troubleshoot what may be going on. 

`hvg` is a character vector containing the highly variable genes to to include in the model. Ideally you would use the ~3.000 most HVG  from the SC dataset to complement the gene set of marker genes identified with `scoreMarkers`. Since in your case there is very little overlap between the `scoreMarkers` genes and the ST data I suggest you either set less stringent parameters when filtering the marker genes or  pass the full list of intersecting genes between your SC and SP data to `hvg`. This way SPOTlight has enough features  to work with, the gene set is ultimately selected by doing `union(unique(mgs[, gene_id]), hvg)`. 

I'm curious to see how it runs on FFPE samples when there is little overlap on the genes, please let me know how it goes!

**Comment by rocketeer1998** [comment]
After trying this
```
sc.st.inter <- union(unique(rownames(merge.sce)), unique(rownames(merge.Visium)))

res <- SPOTlight(
  x = merge.sce,
  y = merge.Visium,
  groups = merge.sce$labels,
  mgs = mgs_df,
  hvg = sc.st.inter,
  weight_id = "mean.AUC",
  group_id = "cluster",
  gene_id = "gene")
```
I can start to run for a second but another error comes out:
```
Scaling count matrix
Seeding initial matrices
Error in split.default(seq_len(nc), groups) : 
  group length is 0 but data length > 0

```

What's the meaning?

**Comment by MarcElosua** [comment]
hi @rocketeer1998 sorry for the delay in replying. Does the variable "cluster" exist in mgs_df? It seems like it is trying to split the dataframe by groups but it can't find the grouping column ("cluster").
