### ISSUE TITLE
"Preparing Gene set" error

### ISSUE THREAD

**Issue by jnmark** [MarcElosua/SPOTlight#5]
Hello,

I am trying to follow through the tutorial as is on the main page, I downloaded the data directly from the 'sample data' directory. All processing steps prior to running the deconvolution are perfect, however while running the spotlight_deconvolution step, I get an error: 

Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
[1] "Preparing Gene set"
Error in rowSums(mtrx_spatial == 0) : 
  'x' must be an array of at least two dimensions

Could you please assist me with resolving this? Please let me know what further information you could need. Thanks!

**EDIT:** I also tried directly loading the spotlight_ls_anterior.rds file provided. On doing that, when I plot the scatterplot using spatial_scatterpie, I get an error:
Error in is.data.frame(col_df) : object 'col_df' not found

**Comment by daisydan20** [comment]
I'm getting the exact same error with the deconvolution step on R 3.6.2. Please let me know if there's any way to resolve this. Thank you so much!

**Comment by MarcElosua** [comment]
Hi @jnmark and @daisydan20 , 
Thanks so much for using SPOTlight and for the heads up!

If you reinstall it via `devtools::install_github("https://github.com/MarcElosua/SPOTlight")` everything should be back to normal. 
It seems there was a problem when using sparse matrices, it should be fixed now.

Sorry for any inconvenience this has caused, please let me know if you have any other issues!

**Comment by jnmark** [comment]
@MarcElosua Thanks so much. I tested it out today, and it seems to work perfectly now. Also, just a note that the "scatterpie" function isn't included in the Spotlight package. It wasn't a problem at all, and I was easily able to add it in using install.packages, but just thought I'd let you know. 

Thanks for such a great tool!

**Comment by MarcElosua** [comment]
Thanks for the comment!
Just added it to the description and it should be automatically installed from now on.
