### ISSUE TITLE
Is old version of spotlight compatible with R version 4.1.3?

### ISSUE THREAD

**Issue by RahmatpourNasim** [MarcElosua/SPOTlight#50]
Is old version of spotlight compatible with R version 4.1.3?

**Comment by MarcElosua** [comment]
Yes, The old version of SPOTlight should be compatible with R 4.1.3.
Regarding the email you sent me I'll reply here so that anyone can see teh reply in case they have the same issues:

**Comment by MarcElosua** [comment]
Yes, The old version of `SPOTlight` should be compatible with R 4.1.3.

Regarding the email you sent me I'll reply here so that anyone can see the reply in case they have the same issues:
The new verions of `SPOTlight` still has all the visualization options the older version had - you can see how to use them in the [vignette](https://github.com/MarcElosua/SPOTlight/blob/main/vignettes/SPOTlight_kidney.Rmd)

Please let me know if you have any other questions here,
Marc

**Comment by RahmatpourNasim** [comment]
Thanks Marc for responding me. Another thing I realized is that this function "plotSpatialScatterpie" flip the spatial image vertically, I tried to convert the "col" to negative in image coordinates but that change the orientation horizontally. This actually was done easily in seurat image. any suggestion for that?
Also the old version has this function in which specific cells of interest only shown as scatterpie on spatial plot. I am wondering if something similar is doable in the updated version? 

```
SPOTlight::spatial_scatterpie(se_obj = anterior,
                              cell_types_all = cell_types_all,
                              img_path = "sample_data/spatial/tissue_lowres_image.png",
                              cell_types_interest = "L6b",
                              pie_scale = 0.5)
```

**Comment by RahmatpourNasim** [comment]
ok,  this ggplot option "scale_y_reverse()"  made the orientation correctly  
I still have the second question, I'd appreciate if you can help me.

**Comment by MarcElosua** [comment]
Hi @RahmatpourNasim 

If you just want to plot 1 cell type you can use Seurat's `Seurat::SpatialFeaturePlot()` and it will grab it from the metadata. If you want to plot the spatial scatterpie only with a subset of the deconvoluted cell types you can use `plotSpatialScatterpie()` and pass the vector of cell type of interest to the `cell_types` argument.

**Comment by RahmatpourNasim** [comment]
Thanks @MarcElosua

**Comment by MarcElosua** [comment]
hi @RahmatpourNasim It seems that this solved your question so I'm going to close the issue. Feel free to open it again if you have any follow ups!
