### ISSUE TITLE
Change size pie charts (plotSpatialScatterpie)

### ISSUE THREAD

**Issue by emparbaltasar** [MarcElosua/SPOTlight#51]
Hi,

I am trying to change the size of the pie charts with the argument pie_scale but it doesn't change anything. Would you be able to help with that?

Thank you in advance,
Empar

**Comment by MarcElosua** [comment]
Hi @emparbaltasar,

Thanks a lot for using SPOTlight!

Whe I run `plotSpatialScatterpie` on a test set as follows the pie_scale does seem to work
```
library(SPOTlight)
library(ggplot2)
library(patchwork)
plt1 <- plotSpatialScatterpie(x = x, y = y, pie_scale = 0.5) +
    labs("pie_scale = 0.5")

plt2 <- plotSpatialScatterpie(x = x, y = y, pie_scale = 2) +
    labs("pie_scale = 2")

plt1 | plt2
```

![image](https://user-images.githubusercontent.com/16361091/161082774-4034f4de-6a52-4e60-8af9-01a6a355ae23.png)

Could you please provide a reprex where I can replicate your issue please?

Marc

**Comment by MarcElosua** [comment]
I think I might have spotted what was going wrong, could you try reinstalling SPOTlight from the `bioc` branch like this:

`BiocManager::install("SPOTlight", version = "devel")`

And check if it works now?

**Comment by emparbaltasar** [comment]
Hi Marc,

Thank you for the fast reply.
I can’t install the devel version of SPOTlight because I get this error:

Error: Bioconductor version '3.15' requires R version '4.2'; use `BiocManager::install(version = '3.14')` with R version 4.1; see
  https://bioconductor.org/install <https://bioconductor.org/install>

I have Bioconductor 3.14 and R 4.1. 

Best,
Empar

**Comment by MarcElosua** [comment]
My apologies, I meant to direct you to this branch where I'm currently developing the code:

`BiocManager::install("SPOTlight", version = "bioc")`

**Comment by emparbaltasar** [comment]
That gives me this error:
`Error: invalid version specification ‘bioc’`

**Comment by MarcElosua** [comment]
Can you try directly from GitHub, we are finalizing the steps to submit it to Bioconductor but we're not fully accepted.

`devtools::install_github("https://github.com/MarcElosua/SPOTlight", ref = "bioc")`

Sorry for the inconvenience!

**Comment by emparbaltasar** [comment]
That worked, thanks!
