### ISSUE TITLE
Topics to Cell types

### ISSUE THREAD

**Issue by Peter-bbh** [MarcElosua/SPOTlight#52]
Hi,

How do you go from topics to cell types using the SPOTlight code?

When I run the example code (SPOTlight_kidney.Rmd) I only obtain "topics" and not the Cell types, except for the plotTopicProfiles(...facet=TRUE) in the end of section 4.1.

Is it correct that for instance the ScatterPie in section 4.4 show the distribution of topics instead of cell types?

![Section 4 4](https://user-images.githubusercontent.com/70518016/162188292-f2ba32b0-f6d7-45d4-945c-56d3eb3fa0a8.png)

And that the first graph in section 4.1 show topic signatures against topic signatures and not cell types.  Why then specify cell types in the command, plotTopicProfiles( x = mod,   y = sce$free_annotation, ... )?

![Section 4 1 1](https://user-images.githubusercontent.com/70518016/162188198-bd3ab95f-7adc-4ffe-8e17-46445f15f7e6.png)

**Comment by RahmatpourNasim** [comment]
@Peter-bbh I have seen that too, that's how I solved it: 
1) I converted the single cell reference seurat object to singlecell experiment
```{r}
sce <- as.SingleCellExperiment(the_seura_object)
colLabels(sce) <- colData(sce)$(the_annotation_column)
```
2)after running Deconvolution command,  I changed the mat column name
```{r}
colnames(mat) <- unique(sce$the_annotation_column)
```

**Comment by Peter-bbh** [comment]
@RahmatpourNasim 
Thanks for your suggestion. I did consider something like that, but it requires that the column order in mat and the sce annotation are the same. And I failed to convince myself that this is indeed the case.

**Comment by MarcElosua** [comment]
Hi @RahmatpourNasim  and @Peter-bbh ,

Thank you so much for reporting on this issue, I will look into why/where the names are replaced with `topics_*`  and get back to you as soon as possible. For now I would follow the approach suggested by @RahmatpourNasim!

Marc

**Comment by emparbaltasar** [comment]
Hi @MarcElosua,
I am having the same issue. Is there already a more reliable solution than changing the mat column name?

**Comment by MarcElosua** [comment]
Hi @emparbaltasar, could you share which version of SPOTlight you're using? The current version `0.99.11` in bioconductor (and main branch) should have this fixed. Let me know if this works for you.
