### ISSUE TITLE
Does the new spotlight have an improvement over the old in the core algorithm part?

### ISSUE THREAD

**Issue by wfxcode** [MarcElosua/SPOTlight#55]
Hi,
I hope to cite your article.
Can I use spotlight-0.1.7 branch for comparsion in my experiments?

**Comment by MarcElosua** [comment]
Hi @wfxcode,

The current version maintains the core algorithm previously used. You should get the same results between the current version and SPOTlight 0.1.7. The main changes are major re-writes to abide with Bioconductor best practices.

**Comment by wfxcode** [comment]
Thank you for the information.
