### ISSUE TITLE
 Issues using plotSpatialScatterpie() with Seurat

### ISSUE THREAD

**Issue by gpersad** [MarcElosua/SPOTlight#58]
Hi,
I was trying to use SPOTlight on visium data saved as a Seurat object. However, I ran into this issue:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/82057654/172207973-c1938674-7853-4465-8d27-de2dad5f2552.png">

I looked at the code and it seems like the Seurat object x is getting converted into a matrix before the plotImage() step. This was done here when extracting coordinates from the Seurat object: 

<img width="931" alt="image" src="https://user-images.githubusercontent.com/82057654/172208029-a0b5e0c8-035d-467b-ae28-c82d617c769b.png">

This is problematic as extracting the image requires that x remains a Seurat object. 

<img width="953" alt="image" src="https://user-images.githubusercontent.com/82057654/172208095-44aeb7cb-51d7-449e-b39e-3512b229b82f.png">

I tried submitting a PR but didn't have write access. I was able to solve it locally by giving the newly created x matrix a new name instead of replacing the Seurat object. Here’s my session info (sorry it’s so big)

<img width="904" alt="image" src="https://user-images.githubusercontent.com/82057654/172207856-a0717535-22e4-4265-9a43-f648324a0cac.png">

**Comment by MarcElosua** [comment]
Hi @gpersad
Thank you so much for reaching out with the feedback!
Great point, I don't know how this escaped out units tests... I will look into and let you know when its fixed!

**Comment by MarcElosua** [comment]
Hi @gpersad 

This should now be fixed on the main branch in github, I will be pushing it to Bioconductor in the next few days! Thanks for spotting it and reaching out!
You can install it form github as follows:
```
devtools::install_github("https://github.com/MarcElosua/SPOTlight")
devtools::install_git("https://github.com/MarcElosua/SPOTlight")
```

Let me know if it now works for you!
