### ISSUE TITLE
Assay Parameter not working in SPOTlight function

### ISSUE THREAD

**Issue by czackl** [MarcElosua/SPOTlight#59]
Hi there, 

i think there is an issue with the SPOTlight() function and the contained trainNMF() call. 
The parameter "assay" is missing in the trainNMF() call and therefore it is not possible to use a Seurat with an assay named other than "RNA". Logically this error does not appear when calling trainNMF() and runDeconvolution() separately while specifying the assay name.

The parameter "assay" should be passed in this function call: 
https://github.com/MarcElosua/SPOTlight/blob/87534b92311aec0f254297dcb9478e4b63e9ee81/R/SPOTlight.R#L103

Greetings and thanks, 
Constantin

Edit: more like a general idea: It might be useful to have separate parameters assay/slot for the single cell and the spatial dataset as the assays may be named differently (like in my case :see_no_evil:). This involves the .extract_counts() calls in Lines 114 and 117 using the same variables.
 https://github.com/MarcElosua/SPOTlight/blob/87534b92311aec0f254297dcb9478e4b63e9ee81/R/trainNMF.R#L114

**Comment by MarcElosua** [comment]
hi @constantin-zackl 

Thank you so much for reaching out! I have added the parameters to `trainNMF` and have also implemented your suggestion :eyes: ! Now you can pass specific assays for the single cell and  and spatial objects through assay_(sc/sp) and slot_(sc/sp).

I will push the changes to Bioconductor in the next few days but you should be able to install it from github
```
devtools::install_github("https://github.com/MarcElosua/SPOTlight")
devtools::install_git("https://github.com/MarcElosua/SPOTlight")
```

**Comment by czackl** [comment]
Wow, thanks!!! That was fast. It works for me now. Have a great weekend!
