### ISSUE TITLE
Questions about the workflow of SPOTlight

### ISSUE THREAD

**Issue by YMSWhuang** [MarcElosua/SPOTlight#65]
Hello,
Thanks for this very useful tool your design.
I have a question about the workflow of SPOTlight

> res <- SPOTlight(
+   x = scRNA_mouse, # Seurat Object for scRNA-Seq
+   y = KD_2@assays$Spatial@counts, # spatail counts
+   groups = as.character(scRNA_mouse$cluster_annotated_general), # annotation of scRNA-Seq
+   mgs = all.markers, # result from FindAllmarkers
+   hvg = 2000,
+   weight_id = "avg_log2FC", # weights (e.g., logFC, -log(p-value))
+   group_id = "cluster", # group labels
+   gene_id = "gene") # gene identifiers

but it always has a bug which I can't deal with it

Error in trainNMF(x = x, y = y, groups = groups, mgs = mgs, n_top = n_top,  : 
  groups %in% mgs[[group_id]] are not all TRUE

maybe I write an wrong group_id? So I check my colnames in the dataframe of "all.markers"

> colnames(all.markers)
[1] "p_val"      "avg_log2FC" "pct.1"      "pct.2"      "p_val_adj"  "cluster"    "gene"   

So what's the reason of this error? Thanks

**Comment by MarcElosua** [comment]
Hi @YMSWhuang 

Thank you very much for your interest on SPOTlight! My best guess is that one of the cell types doesn't have any marker genes.
What happens when you do:
```
unique(as.character(scRNA_mouse$cluster_annotated_general)) %in% unique(all.markers$cluster)
```
It should be all true since SPOTlight needs marker genes for each cell type to initialize the matrix prior to factorization. If this is the issue you can add a row/s to `all.markers` with genes representative of the missing population with dummy numbers for `avg_log2FC`.

Let me know if this helps!

**Comment by YMSWhuang** [comment]
That's great answer! I checked my scRNA_mouse$cluster_annotated_general and "cluster" in my all.markers, and I found something differences in these cell types. Thanks.

**Comment by SuqinYang** [comment]
Hi,
 Thanks for this very useful tool your design! I'm having the same question.I don't know how to solve it. Thanks a lot.
The error:
>res <- SPOTlight(x = sce,
  y = spe,
  groups =as.character(sce$cell_type_sub),
  mgs =cluster_markers_all_1 , #mgs_df,
  #hvg = hvg,
  #weight_id = "mean.AUC",
  group_id = "cluster",
  gene_id = "gene")

Error in trainNMF(x = x, y = y, groups = groups, mgs = mgs, n_top = n_top,  : 
  ids %in% names(mgs) are not all TRUE


>names(cluster_markers_all_1)
[1] "p_val"      "avg_log2FC" "pct.1"      "pct.2"      "p_val_adj"  "cluster"    "gene" 

 >unique(sce$cell_type_sub)%in%unique(cluster_markers_all_1$cluster)
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[19] TRUE TRUE TRUE TRUE TRUE TRUE

**Comment by MarcElosua** [comment]
Hi @SuqinYang ,

My best guess is that the `weight_id` parameter should be set to `avg_log2FC` since as you have it currently set up SPOTlight is looking for a `weight` column.

Hope this helps!
Marc

**Comment by SuqinYang** [comment]
The problem is solved. Thank you so much!
