### ISSUE TITLE
Question about SPOTlight_deconvolution_analysis

### ISSUE THREAD

**Issue by hoon2577** [MarcElosua/SPOTlight#66]
Hi,
I was trying to follow SPOTlight_deconvolution_analysis with PDAC (https://github.com/MarcElosua/SPOTlight_deconvolution_analysis) and i faced an error in '1a-PDAC_paired_deconvolution.Rmd'.

I used data GEO accession number GSE111672 and also was aware of the discrepancy between raw data (GSE111672) and the data in that code as you mentioned.

The question is when i use
`st_b_list <- sapply(sample_pdac_b, USE.NAMES = TRUE, function(geo) ......`

the Seurat object in st_b_list (such as st_b_list$GSM3036911 ) Seurat object doesn't recognize the image

```
> st_a_list$GSM3036911
An object of class Seurat 
25753 features across 956 samples within 1 assay 
Active assay: RNA (25753 features, 0 variable features)
```
```
> st_a_list$GSM3036911@images
[[1]]
rastergrob[GRID.rastergrob.11]
```
```
> Seurat::Images(st_a_list$GSM3036911)
NULL
```

Is there any idea that i can make proper Seurat Object with image?

Also, i think not raw data but processed data that you used (such as single cell annotation or filtered spatial data) is proper for trying SPOTlight_deconvolution_analysis. So, is it possible to offer the real data that you used for me?
Thanks.

**Comment by MarcElosua** [comment]
Hi @hoon2577, 
You should be able to download the processed data from this [link](https://crgcnag-my.sharepoint.com/:f:/g/personal/melosua_crg_es/EgqkdTRqeDFNkecpKmyQNOEB4WOjVerwccTL28KsPvGnww?e=JC6zJD). `PDAC-*_ST_list.RDS` contains a list with the spatial data for each slide and `PDAC-*_itai_joint.RDS` contains the single cell data.
Let me know if this works.

**Comment by 13198910213** [comment]
Hello Author, First of all, congratulations on the successful completion of this outstanding work. I have the same trouble as the previous commenter, the ST data of PDAC is not available for Seurat related operations. I got the data from the URL you provided at https://crgcnag-my.sharepoint.com/:f:/g/personal/melosua_crg_es/EgqkdTRqeDFNkecpKmyQNOEB4WOjVerwccTL28KsPvGnww?e=JC6zJD 
But in the subsequent operation, it still reports an error: Non-S4 category objects (category "rastergrob") do not have a slot for "coordinates".
 Can you please provide me with the ST data of PDAC that is compatible with Seurat operation?

**Comment by MarcElosua** [comment]
hi @13198910213 

I never transitioned the ST data for the PDAC samples,  I used the [Spaniel](https://rdrr.io/bioc/Spaniel/) format.
See the discussion at the time [here](https://github.com/satijalab/seurat/issues/2790) and the tips people had to convert it.

Hope this helps!

**Comment by 13198910213** [comment]
> 你好
> 
> 我从未转换过PDAC样本的ST数据，我使用了[Spaniel](https://rdrr.io/bioc/Spaniel/)格式。在此处[查看当时的讨论](https://github.com/satijalab/seurat/issues/2790)以及人们必须转换它的提示。
> 
> 希望这有帮助！

Dear Professor.
Hello, thank you very much for your reply, but I am sorry that I still don't know what to do with the ST data of PDAC. From the address you provided https://crgcnag-my.sharepoint.com/:f:/g/personal/melosua_crg_es/EgqkdTRqeDFNkecpKmyQNOEB4WOjVerwccTL28KsPvGnww?e=JC6zJD下载的 ST data (PDAC-*_ST_list.RDSPDAC-*_itai_joint.RDS) is also not available, its data format is not Seurat object, but rasterized data. How can I convert it to Seurat object? I look forward to your reply!


PDAC-A_ST_list.RDS：
![1](https://github.com/MarcElosua/SPOTlight/assets/90313160/7e5b8b66-9b9b-452e-876c-57a33191ba9f)
I need the ST data in the following format:
![2](https://github.com/MarcElosua/SPOTlight/assets/90313160/308625a8-e939-4c28-97f2-e97d8ad44040)

**Comment by 13198910213** [comment]
> 嗨，您应该能够从此[链接](https://crgcnag-my.sharepoint.com/:f:/g/personal/melosua_crg_es/EgqkdTRqeDFNkecpKmyQNOEB4WOjVerwccTL28KsPvGnww?e=JC6zJD)下载处理后的数据。 包含一个列表，其中包含每张幻灯片的空间数据，并包含单个单元格数据。让我知道这是否有效。`PDAC-*_ST_list.RDS``PDAC-*_itai_joint.RDS`



> 嗨，您应该能够从此[链接](https://crgcnag-my.sharepoint.com/:f:/g/personal/melosua_crg_es/EgqkdTRqeDFNkecpKmyQNOEB4WOjVerwccTL28KsPvGnww?e=JC6zJD)下载处理后的数据。 包含一个列表，其中包含每张幻灯片的空间数据，并包含单个单元格数据。让我知道这是否有效。`PDAC-*_ST_list.RDS``PDAC-*_itai_joint.RDS`

The ST data downloaded here is rasterized image data and does not apply to Seurat objects, need your further help, thanks!

**Comment by 13198910213** [comment]
> hi @13198910213
> 
> I never transitioned the ST data for the PDAC samples, I used the [Spaniel](https://rdrr.io/bioc/Spaniel/) format. See the discussion at the time [here](https://github.com/satijalab/seurat/issues/2790) and the tips people had to convert it.
> 
> Hope this helps!



Dear Professor.
Hello, thank you very much for your reply, but I am sorry that I still don't know what to do with the ST data of PDAC. From the address you provided https://crgcnag-my.sharepoint.com/:f:/g/personal/melosua_crg_es/EgqkdTRqeDFNkecpKmyQNOEB4WOjVerwccTL28KsPvGnww?e=JC6zJD下载的 ST data (PDAC-*_ST_list.RDSPDAC-*_itai_joint.RDS) is also not available, its data format is not Seurat object, but rasterized data. How can I convert it to Seurat object? I look forward to your reply!


PDAC-A_ST_list.RDS：
![1](https://github.com/MarcElosua/SPOTlight/assets/90313160/7e5b8b66-9b9b-452e-876c-57a33191ba9f)



I need the ST data in the following format:
![2](https://github.com/MarcElosua/SPOTlight/assets/90313160/308625a8-e939-4c28-97f2-e97d8ad44040)

**Comment by 13198910213** [comment]
> Hi @hoon2577, You should be able to download the processed data from this [link](https://crgcnag-my.sharepoint.com/:f:/g/personal/melosua_crg_es/EgqkdTRqeDFNkecpKmyQNOEB4WOjVerwccTL28KsPvGnww?e=JC6zJD). `PDAC-*_ST_list.RDS` contains a list with the spatial data for each slide and `PDAC-*_itai_joint.RDS` contains the single cell data. Let me know if this works.

The ST data downloaded here is rasterized image data and does not apply to Seurat objects, need your further help, thanks!

**Comment by MarcElosua** [comment]
Hi @13198910213,

Thank you for your interest in the data we used in SPOTlight's paper. 
We did not generate this data, it was already publicly available after being originally published [here](https://pubmed.ncbi.nlm.nih.gov/31932730/). We never converted the data to Seurat, instead we worked with it using the Spaniel package so I cannot help you in the conversion process. For the image, however, it is fairily straight forward to convert the raster format to others, I believe to convert the image to a Seurat-friendly format you can try `img <- as.matrix(img)`

Hope this helps!
Marc

**Comment by 13198910213** [comment]
Dear Professor.
Thank you very much for your prompt reply. I still need your help. Can you please share the processed ST data (filtered_feature_bc_matrix.tsv, tissue_positions_list_spatial_object.tsv, lowres_rot.jpg) with me? My email address is ***@***.*** I sincerely look forward to hearing from you.
Sincerely,&nbsp;
Dr. Lee





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MarcElosua/SPOTlight"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月12日(星期五) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MarcElosua/SPOTlight] Question about SPOTlight_deconvolution_analysis (Issue #66)





 
Hi @13198910213,
 
Thank you for your interest in the data we used in SPOTlight's paper.
 We did not generate this data, it was already publicly available after being originally published here. We never converted the data to Seurat, instead we worked with it using the Spaniel package so I cannot help you in the conversion process. For the image, however, it is fairily straight forward to convert the raster format to others, I believe to convert the image to a Seurat-friendly format you can try img <- as.matrix(img)
 
Hope this helps!
 Marc
