### ISSUE TITLE
Question about accessing older versions of SPOTlight

### ISSUE THREAD

**Issue by anjrao17** [MarcElosua/SPOTlight#67]
Hi, I am trying to access an older version (0.1.7) that is compatible with R 4.0.5 but unable to download from the github repo. Can you point to where I can get this ?

Thanks!
Anjali

**Comment by MarcElosua** [comment]
Hi @anjrao17, SPOTlight version 0.1.7 can still be accessed from the github branch `spotlight-0.1.7`.
You can install it using the following command:
`devtools::install_github("https://github.com/MarcElosua/SPOTlight", ref = "spotlight-0.1.7")`

Let me know if this works!

**Comment by xiaojjia** [comment]
Hi, I've tried to download `spotlight-0.1.7` as you said, but it failed. Maybe I need another way to download?

Thanks！

**Comment by MarcElosua** [comment]
Hi @xiaojjia could you post what error you're getting?

**Comment by xiaojjia** [comment]
> Hi @xiaojjia could you post what error you're getting?

Sorry, I fogot to post it,  but it worked now! maybe because of the network, causing it failed to download before. Thanks a lot!
