### ISSUE TITLE
problem with plotTopicProfiles: Error in plotTopicProfiles(x = mod, y = sce$Cell_Type, facet = FALSE,  :    is(x, "NMFfit") is not TRUE

### ISSUE THREAD

**Issue by ultimatex5** [MarcElosua/SPOTlight#68]
Hi',

thanks for your good work!
I'm following the tutorial at (https://github.com/MarcElosua/SPOTlight/blob/main/vignettes/SPOTlight_kidney.Rmd)
and after I create the trained model in two step to use later for other samples with:
```
mod_ls <- trainNMF(
    x = sce,
    y = spe,
    groups = sce$Cell_Type,
    mgs = mgs_df,
    weight_id = "mean.AUC",
    group_id = "cluster",
    gene_id = "gene")
```
and run the deconvolution:
```
res <- runDeconvolution(
    x = spe,
    mod = mod_ls[["mod"]],
    ref = mod_ls[["topic"]])
```
I extract the deconvolution matrix:
```
mat <- res$mat
dim(mat)
[1] 744  45
```
and the NMF model fit:
```
mod <- res$NMF
dim(mod)
NULL
str(mod)
NULL 
```
I notice that res has not a NMF slot:
```
str(res)
List of 2
$ mat
$ res_ss
```

so I tried to plot topic profiles but I have always the same error:

_Error in plotTopicProfiles(x = mod, y = sce$Cell_Type, facet = FALSE,  : 
  is(x, "NMFfit") is not TRUE_

do you know why it happens?

**Comment by ultimatex5** [comment]
Add infos:
1)  SPOTlight is installed with:
```
library(devtools)
install_github("https://github.com/MarcElosua/SPOTlight")
```
2) version = SPOTlight_1.0.1
3) if I run the command not split in 2 parts I obtain the right output and _res_ has the NMF slot:
```
res <- SPOTlight(
    x = sce,
    y = spe,
    groups = as.character(sce$Cell_Type),
    mgs = mgs_df,
    hvg = hvg,
    weight_id = "mean.AUC",
    group_id = "cluster",
    gene_id = "gene")
```

**Comment by MarcElosua** [comment]
Hi @ultimatex5

Thank you so much for your interest in SPOTlight! When you carry out the analysis in 2 steps `runDeconvolution` doesn't return the model since you already obtained it from the `trainNMF` function and you pass it as `mod_ls[["mod"]]`. In this case you would need to pass  `mod_ls[["mod"]]` to x in `plotTopicProfiles`. 

Hope this helps! Let me know if you have any issues!

**Comment by ultimatex5** [comment]
solved thanks
