### ISSUE TITLE
deconvolution with the same reference

### ISSUE THREAD

**Issue by MigleMi** [MarcElosua/SPOTlight#69]
Thank you for this amazing tool! I have tried it out on my data and SPOTlight function worked beautifully on individual samples, however, I would like to train a model on one sample and use it for other sample deconvolution, is it possible to do that or training must be done on merged spatial data from samples of interest? The problem is that I have datasets in different locations and I could only transfer the model and not the ST data. Could you please clarify the workflow with the model training? I think this got me confused: "the trained model allows you to reuse with other datasets you also want to deconvolute with the same reference" 

The issue I have encountered was this:
`rAdjacent_Normal <- runDeconvolution(spot_counts, mod = mod_ls[["mod"]], ref = mod_ls[["topic"]], verbose=TRUE)`
`Error in nnls(W, x[, i]) : NA/NaN/Inf in foreign function call (arg 5)` 

the model only works for the spatial data that was trained on. 

Also, I have a question about the reference sce, I do not have all the cells of interest from one sequenced sample, only from multiple samples that I have integrated into one reference. Is there a possibility to somehow merge these different cell types to get a full picture of the possible cell types in ST data and minimise any batch effects?

Thank you again!

**Comment by ultimatex5** [comment]
Hello',
same problem here: I have 4 spatial samples and 1 single cell reference. Before starting I checked the union between the genes of all 4 spatial samples using intersect and the genes are always the same (so i thought when i trained the model on a spatial sample i could use it with the others).
But the model only works for the spatial data that was trained on and I have the error:

`Error in nnls(W, x[, i]) : NA/NaN/Inf in foreign function call (arg 5)
`

**Comment by MarcElosua** [comment]
Hi @MigleMi & @ultimatex5,

I will look into this in more detail and get back to you! Thank you for your interest in SPOTlight and for reporting this!!

marc

**Comment by MarcElosua** [comment]
Getting back to this --

When I use toy data to run `trainNMF` with one `SpatialExperiment` (SE) and then run `runDeconvolution` with the same and other SE I have no issues with my output. See toy example below:
```
set.seed(321)
# mock up some single-cell, mixture & marker data
sce <- mockSC(ng = 200, nc = 10, nt = 3)
mgs <- getMGS(sce)
spe <- mockSP(sce)
meta <- metadata(spe)
spe2 <- mockSP(sce)
meta2 <- metadata(spe2)

cd <- DataFrame(x = seq(ncol(spe)), y = seq(ncol(spe)), z = sample(z, 100, replace = TRUE))
y <- as.matrix(counts(spe))
spe <- SpatialExperiment(
    assay = list("counts" = y),
    colData = cd,
    spatialCoordsNames = c("x", "y"))

cd <- DataFrame(x = seq(ncol(spe2)), y = seq(ncol(spe2)), z = sample(z, 100, replace = TRUE))
y <- as.matrix(counts(spe2))
spe2 <- SpatialExperiment(
    assay = list("counts" = y),
    colData = cd,
    spatialCoordsNames = c("x", "y"))

################################
#### Run SPOTlight by steps ####
################################
set.seed(687)
# Train NMF
mod_ls <- trainNMF(
    x = sce,
    y = spe,
    groups = sce$type,
    mgs = mgs,
    weight_id = "weight",
    group_id = "type",
    gene_id = "gene"
)

# Run deconvolution on 2 different SpatialExperiment objects
res1 <- runDeconvolution(
    x = spe,
    mod = mod_ls[["mod"]],
    ref = mod_ls[["topic"]])

res2 <- runDeconvolution(
    x = spe2,
    mod = mod_ls[["mod"]],
    ref = mod_ls[["topic"]])

# (Check the predictions make sense)
(mse <- mean((res1[["mat"]] - meta$props)^2))
(mse2 <- mean((res2[["mat"]] - meta2$props)^2))
```

Could you please specify the version of SPOTlight you are running and try to see if running this example works?
One thing you can try is to make sure there are rows that are not all 0s in your SE objects.

Let me know if the above toy example works and your version to see what can be causing this!

**Comment by MarcElosua** [comment]
For @MigleMi , on your question - 

> *Also, I have a question about the reference sce, I do not have all the cells of interest from one sequenced sample, only from multiple samples that I have integrated into one reference. Is there a possibility to somehow merge these different cell types to get a full picture of the possible cell types in ST data and minimise any batch effects?*

There is no issue with using an integrated reference datasets, my recommendation would be to try to minimize the batch effect within each cell type by selecting up to 100 cells / cell type coming from the minimum number of batches possible.

Hope this helps!

**Comment by ultimatex5** [comment]
> y <- as.matrix(counts(spe))
> spe <- SpatialExperiment(
>     assay = list("counts" = y),
>     colData = cd,
>     spatialCoordsNames = c("x", "y"))

Hi,
thanks for your answer;
the version of SPOTlight that I'm using is SPOTlight_1.0.1
About your example I've problem with
`cd <- DataFrame(x = seq(ncol(spe2)), y = seq(ncol(spe2)), z = sample(z, 100, replace = TRUE))`
and i obtain the error
`Error in sample(z, 100, replace = TRUE) : object 'z' not found`
because you have forget to define `z`

**Comment by MarcElosua** [comment]
Apologies, you can use `z = letters`. Z is just a dummy variable to be filled with anything in this example.

**Comment by ultimatex5** [comment]
> Could you please specify the version of SPOTlight you are running and try to see if running this example works? One thing you can try is to make sure there are rows that are not all 0s in your SE objects.
> 
> Let me know if the above toy example works and your version to see what can be causing this!

I've try with your dummy data and all is fine.
I've also checked and I have a lot of rows in the spatial dataset with all 0s (ie. more or less 50% of genes that are not expressed in any spot); do you suggest to remove those rows before to train the model?
Thanks
