### ISSUE TITLE
data links in README don't work - release data with package

### ISSUE THREAD

**Issue by drighelli** [MarcElosua/SPOTlight#7]
you can release the data into your package by putting them into the `inst` folder of your package.

If you would like to keep the data light you'd use just a subset of 'em.

Once, installed you can retrieve them with the system.files(package="SPOTlight") function.

Dario

**Comment by MarcElosua** [comment]
Hi @drighelli,
Sorry for the delayed response. I have modified the README and added the sample_data to inst so it wil lbe installed upon installation.
Thanks for your input!
Marc
