### ISSUE TITLE
Issue plotSpatialScatterpie with a SpatialExperiment object

### ISSUE THREAD

**Issue by Zifeng-L** [MarcElosua/SPOTlight#70]
Hi there,
I just want to plot a scatterpie with the axis from the mirror img. 
```
plotSpatialScatterpie(
        x = spe,
        y = mat,
        cell_types = colnames(mat),
        img = TRUE,
        slice = SpatialExperiment::imgData(spe)[1, "sample_id"],
        scatterpie_alpha = 1,
        pie_scale = 0.4,
        axis = "h"
    )
```
I keep getting this error:
<img width="504" alt="1660145062093" src="https://user-images.githubusercontent.com/53402047/183943508-c13c745c-d079-4e09-a92e-e83f9e01f0b4.png">

any help? Many thanks in advance.

**Comment by MarcElosua** [comment]
Hi @Zifeng-L,

For me it works well when I pass a a SpatialExperiment object. Can you please return what class spe is?
You can also try passing the image object directly to the parameter `img = SpatialExperiment::imgRaster(spe, sample_id = slice)`

Hope this helps!

**Comment by criphg** [comment]
Same problem here.
class(spe) = "SpatialExperiment",
when use imgRaster(spe) in place of True only show part of image, and lost of pie chart information.
The image looks good in plot(imgRaster(spe)).

Any help would be appreciated.

**Comment by MarcElosua** [comment]
Hi @criphg could you please share a reprex so I can look into this?
Have you tried passing the image object directly to the img parameter - `img = SpatialExperiment::imgRaster(spe, sample_id = slice)`
Thank you!
