### ISSUE TITLE
Deconvolution cannot identify tumor cell type in tumor spatial data

### ISSUE THREAD

**Issue by hansong798** [MarcElosua/SPOTlight#71]
Hello, thank you for developing useful package.

I tried to find cell type composition of each spot on spatial data and used SPOTlight.
However, after running, it did not include tumor cell type in any tumor region.

![image](https://user-images.githubusercontent.com/85104781/185349640-70df93a5-962c-4d5d-a58e-5f29c428606e.png)

I followed downsampling as described in tutorial, but only difference in my codes are I used "mean.AUC > 0.7" and added set.seed function.

```
sce <- logNormCounts(sce)
dec <- modelGeneVar(sce)
hvg <- getTopHVGs(dec, n = 3000) 
colLabels(sce) <- colData(sce)$sub.celltype

genes <- !grepl(pattern = "^Rp[l|s]|Mt", x = rownames(sce))
mgs <- scoreMarkers(sce, subset.row = genes)
mgs_fil <- lapply(names(mgs), function(i) {
  x <- mgs[[i]]
  x <- x[x$mean.AUC > 0.7, ]  ### i use 0.7
  x <- x[order(x$mean.AUC, decreasing = TRUE), ] 
  x$gene <- rownames(x)
  x$cluster <- i
  data.frame(x)
})
mgs_df <- do.call(rbind, mgs_fil)
table(mgs_df$cluster)


idx <- split(seq(ncol(sce)), sce$sub.celltype)
n_cells <- 100
set.seed(123)
cs_keep <- lapply(idx, function(i) {
  n <- length(i)
  if (n < n_cells)
    n_cells <- n
  sample(i, n_cells)
})
sce <- sce[, unlist(cs_keep)]

mod_ls_Pri1 <- trainNMF(
  x = sce,
  y = spe_Pri1,
  groups = sce$sub.celltype,
  mgs = mgs_df,
  weight_id = "mean.AUC",
  group_id = "cluster",
  gene_id = "gene")

res_Pri1 <- runDeconvolution(
  x = spe_Pri1,
  mod = mod_ls_Pri1[["mod"]],
  ref = mod_ls_Pri1[["topic"]])
mat_Pri1 <- res_Pri1$mat
```

When i tried to use other options of 'weight_id', it did not catch tumor cell type as well.

Is there another way to try or am I missing something?

**Comment by MarcElosua** [comment]
hi @hansong798, thank you so much for your interest in SPOTlight and for reaching out!

Would it be possible to see how the topic profiles look for each cell type? Maybe there is an overlap between the topics learned for CAFs and tumor cells and the former is capturing all the signal. It would also be interesting to look at which genes are the most important for the topics associated with tumor cells and assess if they makes sense.

**Comment by justinesjw** [comment]
Dear Marc, 

Thank you for developing SPOTlight! Really love the idea of NMF and the visualization of results!

I faced the same issue while training the model on the whole atlas. When I increase the number of cells included in reference object, the predicted cell type proportion changed drastically. May I know your thoughts on this? In your paper, I noticed you separately trained the model on a more specific immune atlas. Do you think that will help in this case? Also, how do you usually filter the markers you feed the model? Do you filter for positive logFoldChange genes and limit to maybe top 50 or 100 genes? for weightage of gene, do you recommend using pvalues or logfoldchange (do we include negative values?)?

Sorry for so many questions! Would really appreciate to know your thoughts/recommendations on these 😁 

Thank you again!

Best Regards, 
Justine
