### ISSUE TITLE
Suspected incorrect variable names used in vignette

### ISSUE THREAD

**Issue by Nick-Eagles** [MarcElosua/SPOTlight#72]
Hello,

I've been following along with the [Bioc release vignette](https://bioconductor.org/packages/release/bioc/vignettes/SPOTlight/inst/doc/SPOTlight_kidney.html) and encountered an error at this code chunk:

```
mod_ls <- trainNMF(
    x = sce,
    y = spe,
    groups = sce$type,
    mgs = mgs,
    weight_id = "weight",
    group_id = "type",
    gene_id = "gene")
```

I suspect a couple variable names are mistaken here; for example, `sce$type` is not a column in the `colData`:

```
> sce$type
NULL
```

I changed the first code chunk to the following to solve the issue:

```
mod_ls <- trainNMF(
    x = sce,
    y = spe,
    groups = as.character(sce$free_annotation),
    mgs = mgs_df,
    weight_id = "mean.AUC",
    group_id = "cluster",
    gene_id = "gene"
)
```

Thanks for providing SPOTlight and let me know if I can provide more information.

Best,

-Nick

**Comment by MarcElosua** [comment]
Hi @Nick-Eagles,

Yes! You're right, thank you so much for spotting this! I will fix it in the next release!
