### ISSUE TITLE
Convert mgs to data.frame

### ISSUE THREAD

**Issue by nesilin** [MarcElosua/SPOTlight#75]
Hi Marc,

Nice tool! Please be aware that mgs must be converted into data.frame since tibble seems not to work.

Thanks!

**Comment by MarcElosua** [comment]
Hi @nesilin,

Thank you so much for your input and for digging into the code! This bug has been fixed [here](https://github.com/MarcElosua/SPOTlight/blob/bioc_rcpp/R/trainNMF.R#L76).

Please let me know if you have any further questions/issues!
