### ISSUE TITLE
export SPOTlight results to 10x Genomics Loupe Browser

### ISSUE THREAD

**Issue by sdwien** [MarcElosua/SPOTlight#76]
Dear SPOTlight team (and users),

I have just used SPOTlight for the first time successfully, and processed a 10x Genomics Visium data set.

I am working in a core facility and would like to share some of the results with our users so that they can browse them by themselves in the 10x Genomics Loupe Browser.

On other occasions, I have exported 2-column files of barcodes and annotations (or other metadata) from R and loaded them in the Loupe Browser via the "Import categories" option.
In the case of the SPOTlight results, I was considering to export similar files, one for each cell type used in the deconvolution, containing the proportions of this cell type for all barcodes. This would mean loading 10-20 files in Loupe, which can then be visualized only one at a time.

On the other hand, the scatter pie visualization is quite comprehensive (even though it is not interactive).

Have some of you exported data from SPOTlight to Loupe, and how have you done it?

Thanks a lot for the inspiration and for an straight-forward to use tool!

Best regards,
Sophia

**Comment by MarcElosua** [comment]
Hi @sdwien,

Thank you for your interest in SPOTlight and for your kind words! Unfortunately we have not exported SPOTlight's results to the Loupe browser so unfortunately we have no experience with this. However, as 10X suggests [here](https://support.10xgenomics.com/single-cell-gene-expression/software/visualization/latest/tutorial-interoperability) it maybe be worth trying to load 1 file with 10-20 columns and see if the Loupe browser can process it!

Please do follow up on which approach ends up working best for you in this issue!

Thanks a lot, Marc

**Comment by sdwien** [comment]
Dear Marc,
thanks for your reply and suggestions.
For the time being, it is only possible to import projections (x-y coordinates of dim. red.), "categories" (cluster memberships of spots) and lists of "features" (genes) into Loupe, but not vectors of numeric data for all spots. What happens when one tries to do this, is that since the values are different for each barcode (except for 0), virtually each barcode is assigned a separate category and color in Loupe, which does not fulfill the purpose.
What I have done for now, is to round the proportions for a given cell type as output by SPOTlight to 1 digit, so now I can visualize them in Loupe as only 10 "categories" (0, 0.1, 0.2, 0.3, etc. ... 0.9).
I have been in contact with the 10x development team, and they are putting it on their to-do list.
I'll be happy to keep everyone updated.

Best regards from Vienna to Barcelona,
Sophia

**Comment by MarcElosua** [comment]
That would be great! Thank you very much for sharing your process here, looking forward to seeing if 10X implements this!
