### ISSUE TITLE
colData(sc_data)$subclass

### ISSUE THREAD

**Issue by wang0430** [MarcElosua/SPOTlight#77]
Dear SPOTlight team (and users),

I'm trying to deal with scRNA-seq dataset是, the following problems, don't know is what reason, want to ask you！
![1668161596120](https://user-images.githubusercontent.com/112233361/201318679-e36625aa-8c14-4b41-89f0-4ea03d1476c7.png)

**Comment by MarcElosua** [comment]
Hi @wang0430 

It seems like you're trying to run SingleCellExperiment functions on a Seurat object. You can do the colLabels assignment as 

```
Seurat::Idents(sc_data) <- sc_data$subclass
```

Hope this helps,
Marc
