### ISSUE TITLE
Difference between cell type correlation and cell communication

### ISSUE THREAD

**Issue by wang0430** [MarcElosua/SPOTlight#78]
Spotlight provides the function to analyze the cell type correlation. I'm curious how this differs from cell communication and what the underlying principle is.

**Comment by MarcElosua** [comment]
Hi @wang0430 

Thank you for your interest in SPOTlight! Cell type correlation just looks at how the predicted proportions of cells correlate within each spot. It does not take into account any Ligand-Receptor information.

Hope this helps,
Marc
