### ISSUE TITLE
SPOTlight with low numbers of genes per spot

### ISSUE THREAD

**Issue by sdwien** [MarcElosua/SPOTlight#79]
Dear SPOTlight team,

I am processing a Visium FFPE dataset from a challenging tissue with very low numbers of genes per spot (200 - less than 500 median genes per spot).
What would be your take on this, is this enough information to deconvolute the expression profiles of the spots with SPOTlight?
Would you recommend to adjust some of the default settings of the SPOTlight analysis?
My annotated reference single cell data set has between 400 and 2400 genes per cell.
Looking at the "residuals" plot after running SPOTlight, it looks that except for a few spots with a residual value of between 0.1 and 0.3, all spots are between 0.0 and 0.1 .

Many thanks for your thoughts on this.

Best regards from Vienna, Sophia

**Comment by MarcElosua** [comment]
Hi @sdwien,

As long as there are enough features overlapping between the SC and ST data the deconvolution should be fine. However, from the information I can gather from your issue two possible scenarios could be that the tissue was lowly sequenced or it has low cellular density. Both of these cases will require different interpretations of the deconvolution results relying on your biological expertise!

Hope this helps, Marc
