### ISSUE TITLE
R4.01

### ISSUE THREAD

**Issue by heilandd** [MarcElosua/SPOTlight#8]
Installation in R 4.01 (with dplyr 1.02) is not working or at least causing problems (from github). In my case, the problem is due to some files of the package .RDS files which include an old version of dplyr. Sourcing the code makes it work. Nice package!

**Comment by sengao86** [comment]
Hi Dieter,

can you please specify how to solve the problem? I am running into the same issue with R 4.03

**Comment by MarcElosua** [comment]
Hi @heilandd and @sengao86 sorry for the late response, 
My dplyr version is also 1.0.2 and I have installed SPOTlight on R 4.0.1 without encountering the issue.
Could you please provide a bit more information so I can try to replicate your issue and try to fix it?
Thanks a lot for using SPOTlight!
Marc

**Comment by sengao86** [comment]
devtools::install_github("https://github.com/MarcElosua/SPOTlight")
Downloading GitHub repo MarcElosua/SPOTlight@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/MarcElosua/SPOTlight/tarball/HEAD' failed

**Comment by MarcElosua** [comment]
@sengao86 Could you please specify which operating system you're using?

**Comment by sengao86** [comment]
@MarcElosua 

NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by heilandd** [comment]
I am not 100% sure but the problem are your RDS files in which an old version of dplyr is implemented (in any S4 object for example). If you clone the repository, install oll dependencies and source the code files, it works perfectly! 

```
files_R= dir("~/Desktop/ ... /Spotlight/R") # path to Spotlight R folder
for(i in 1:length(files_R)){source(paste0("~/Desktop/SPATA/Spotlight/",files_R[i]))}
```

**Comment by AMechels** [comment]
Had the same error as @sengao86, changed the command to 
`install_git("https://github.com/MarcElosua/SPOTlight")`
which fixed it
