### ISSUE TITLE
Does the new version of SPOTlight no longer support data from Seurat?

### ISSUE THREAD

**Issue by VivalavidaLu** [MarcElosua/SPOTlight#80]
It is found that the new version of SPOTlight analyze data from singlecellexperiment format, can SPOTlight still support data from seurat?

**Comment by MarcElosua** [comment]
Hi @Lukadon77,
Yes, the bioconductor version of SPOTlight can take in SinglecellExperiment & Seurat objects as well as sparse/dense matrices.
