### ISSUE TITLE
test_spot_fun

### ISSUE THREAD

**Issue by umar1196** [MarcElosua/SPOTlight#82]
Hi,

I am trying to produce the synthetic test mixture using the SPOTlight using the following line:

test.spot.ls1<-SPOTlight::test_spot_fun(se_obj=tem.t1,clust_vr='subclass',n=1000)

but it raised the error: Error: 'test_spot_fun' is not an exported object from 'namespace:SPOTlight'

Please help me to solve it.

**Comment by MarcElosua** [comment]
Hi @umar1196,

The function has been deprecated in updated versions of SPOTlight. Please find the original function [here](https://github.com/MarcElosua/SPOTlight/blob/spotlight-0.1.7/R/test_spot_fun.R).

Best

**Comment by umar1196** [comment]
Problem solved. Thanks
