### ISSUE TITLE
Error  in trainNMF(x = x, y = y, groups = groups, mgs = mgs, n_top = n_top, :  ids %in% names(mgs) are not TRUE

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [MarcElosua/SPOTlight#83]
Hi I wanted to use SPLOTlight on spatial data but I'm facing some issue. can you help me ? 

I run like this : 
```
load("/Users/benjamin/Dropbox (U932)/Salmon team/Data_storage/Seq_data/scRNASeq/public_data/Lung/Grout_Leader_data_dn1000_SCT.RData")
genes <- !grepl(pattern = "^RP[L|S]|MT", x = rownames(Grout_Leader_data))
Grout_Leader_data <- subset(x = Grout_Leader_data, Cell_subtype %in% unique(mgs_df$cluster))
Grout_Leader_data <- subset(x = Grout_Leader_data, Cell_subtype %in% c("Mitocondrials", "Junk"), invert = T)

mgs <- scoreMarkers(as.SingleCellExperiment(Grout_Leader_data), 
                    groups = Grout_Leader_data$Cell_subtype, 
                    BPPARAM=MulticoreParam(parallel::detectCores()))

mgs_fil <- lapply(names(mgs), function(i) {
    x <- mgs[[i]]
    # Filter and keep relevant marker genes, those with AUC > 0.8
    x <- x[x$mean.AUC > 0.8, ]
    if (dim(x)[1]>0) {
      # Sort the genes from highest to lowest weight
      x <- x[order(x$mean.AUC, decreasing = TRUE), ]
      # Add gene and cluster id to the dataframe
      x$gene <- rownames(x)
      x$cluster <- i
      data.frame(x)
    }
})

mgs_df <- do.call(rbind, mgs_fil)

Grout_Leader_data <- subset(x = Grout_Leader_data, Cell_subtype %in% names(mgs))

Grout_Leader_data$Cell_subtype <- as.character(Grout_Leader_data$Cell_subtype)

Idents(Grout_Leader_data) <- as.character(Grout_Leader_data$Cell_subtype)


DefaultAssay(Grout_Leader_data) <- "RNA"
res <- SPOTlight(
    x = Grout_Leader_data,
    y = Plasticity_spatial.integrated,
    groups = as.character(Grout_Leader_data$Cell_subtype),
    mgs = mgs,
    weight_id = "median.AUC",
    group_id = "cluster",
    gene_id = "gene")
```

When I did :
```
names(mgs) %in% unique(Grout_Leader_data$Cell_subtype)
```
I got 

```
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[33] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
```

How can I do ? 

thanks for your help 
 

Both are Seurat object

**Comment by feasiblee** [comment]
Hello, how did you solve it, thank you.

**Comment by MarcElosua** [comment]
Hi apologies for the late response here, would it be possible to get a more extended error message to help me debug this?

**Comment by Duyangl** [comment]
hi，I have the same question,but I have checked all variables.
my codes are as follows 
spa_c1 <- subset(crc_spa, subset = orig.ident == "C1")
SpatialPlot(spa_c1)

Idents(immune_obj) <- immune_obj$celltype

# -------- --------
Idents(immune_obj) <- "celltype"
immune_markers_celltype <- FindAllMarkers(immune_obj, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)


marker_genes_list <- immune_markers_celltype %>%
  filter(p_val_adj < 0.01, avg_log2FC > 0.5) %>%
  group_by(cluster) %>%
  top_n(50, avg_log2FC) %>%
  split(.$cluster) %>%
  lapply(function(df) df$gene)

# --------------
sce_immune <- as.SingleCellExperiment(immune_obj)
sce_spatial <- as.SingleCellExperiment(spa_c1)
assay(sce_immune, "counts") <- as(assay(sce_immune, "counts"), "dgCMatrix")
assay(sce_spatial, "counts") <- as(assay(sce_spatial, "counts"), "dgCMatrix")

# -------- -------
cell_counts <- table(sce_immune$celltype)
cs_keep <- lapply(split(seq(ncol(sce_immune)), sce_immune$celltype), function(i) {
  sample(i, min(length(i), 500))
})
sce_immune_subset <- sce_immune[, unlist(cs_keep)]

common_genes <- intersect(rownames(sce_immune_subset), rownames(sce_spatial))
sce_immune_subset <- sce_immune_subset[common_genes, ]
sce_spatial <- sce_spatial[common_genes, ]

marker_genes_list <- lapply(marker_genes_list, function(genes) intersect(genes, common_genes))
marker_genes_list <- marker_genes_list[sapply(marker_genes_list, length) > 0]
sce_immune_final <- sce_immune_subset[, sce_immune_subset$celltype %in% names(marker_genes_list)]

# -------- -------
res_immune <- SPOTlight(
  x = sce_immune_final,
  y = sce_spatial,
  groups = sce_immune_final$celltype,
  mgs = marker_genes_list,
  hvg = min(2000, nrow(sce_spatial))
)
