### ISSUE TITLE
Parallel run 

### ISSUE THREAD

**Issue by BenjaminDEMAILLE** [MarcElosua/SPOTlight#84]
Hi ! 
How to run SPOTlight in parallel ? 
Thanks

**Comment by MarcElosua** [comment]
Hi @BenjaminDEMAILLE ,

Thank you for your interest in SPOTlight, currently this has not been implemented yet.

If you want to optimize time what I would suggest is training the model once with `trainNMF.R` and using its output to pass it to `runDeconvolution.R` for each visium slide of interest. Make sure the entire gene set used is maintained in the trainNMF step!

Hope this helps

**Comment by BenjaminDEMAILLE** [comment]
Thanks ! I have one Seurat with 4 slides. 

nmf support DoParallel. can you activate it in the future ? 




.pbackend | specification of the foreach parallel backend to register and/or use when running in parallel mode. See options p and P in argument .options for how to enable this mode. Note that any backend that is internally registered is cleaned-up on exit, so that the calling foreach environment should not be affected by a call to nmf – except when .pbackend=NULL.


https://rdrr.io/cran/NMF/man/nmf.html
