### ISSUE TITLE
What does the 'decon_df' mean? 

### ISSUE THREAD

**Issue by White2album** [MarcElosua/SPOTlight#88]
Dear SPOTlight developers,
Hello, I am writing an issue because I have a questions.

I used the 0.1.7 version to get the 'decon_df' data.frame.
And it shows B.cells(0.1027680), T.cells(0.08543332), NK.cells(0.10633517).
Is it means this spatial spot has 10.2% B.cells 8.5% NK.cells 10.6%?
if not, how can I get the proportion of each cells in one spot?

**Comment by MarcElosua** [comment]
That is the correct interpretation yes. A more accurate way to put it would be that what we're predicting is the contribution to the transcriptome of that spot.

**Comment by White2album** [comment]
> That is the correct interpretation yes. A more accurate way to put it would be that what we're predicting is the contribution to the transcriptome of that spot.

Thank you for your answer! And I have  an another question.
I found that the contribution value of some cells during deconvolution is higher than the actual situation. Through the plotTopicProfiles function, I observed that the cell type is expressed in multiple topics. 
May I ask how to correct this situation and how to set a certain threshold to remove the cell type with inaccurate expression? Or for some areas that are not clearly identified, it is defined as unknown, so that I can more accurately predict the contribution of different cell types to spot.

**Comment by MarcElosua** [comment]
Hi @White2album,

The fact that a topic is expressed in multiple topics is not an issue so far as the pattern of topics is specific to that cell type. In the case that 2 cell types have the exact same topic profile pattern then I would think about checking which genes you are passing as markers and try to make a set of them as specific to each cell type as possible.

As for your second point I have found in practice that removing those cell types predicted to be present < 0.03 (3%) is an effective way to remove false positives. However, this is very much context dependent.

Hope this helps!
Marc

**Comment by White2album** [comment]
Thank you for your answer @MarcElosua ,

When I check my single cell data, I found the number of HVG is improtant for spotlight, so I set 'fdr.threshold = 0.05' when using the getTopHVGs function. The result that 91 HVG had found in my data instead of 3000 HVG by defaults.

Further more,  I filtrate the 'mgs_fil' list to ensure  that each cell type has 5~ 15 specific genes.

What do you think of my handling of this?  

Thanks for your kind and considerate help again.

**Comment by MarcElosua** [comment]
If those are clearly distinct cell types that should be enough, if you have more granularity I would suggest just selecting the top 3000HVG as they are usually informative
