### ISSUE TITLE
Error in .extract_counts(y, assay, slot) :    !is.null(colnames(x)) is not TRUE

### ISSUE THREAD

**Issue by carlosccfraga** [MarcElosua/SPOTlight#89]
I am performing SPOTlight and I am getting this error:
Error in .extract_counts(y, assay, slot) :    !is.null(colnames(x)) is not TRUE

I am using this script

sce <- logNormCounts(sce)
dec <- modelGeneVar(sce)
plot(dec$mean, dec$total, xlab = "Mean log-expression", ylab = "Variance")
curve(metadata(dec)$trend(x), col = "blue", add = TRUE)

hvg <- getTopHVGs(dec, n = 3000)
colLabels(sce) <- colData(sce)$cell_type_ord

# Get vector indicating which genes are neither ribosomal or mitochondrial
genes <- !grepl(pattern = "^Rp[l|s]|Mt", x = rownames(sce))

# Any clustering method is okay, only using k-means for convenience.
#kout <- kmeans(t(logcounts(sce)), centers=54) 

mgs <- scoreMarkers(sce, subset.row = genes)

mgs_fil <- lapply(names(mgs), function(i) {
  x <- mgs[[i]]
  # Filter and keep relevant marker genes, those with AUC > 0.8
  x <- x[x$mean.AUC > 0.8, ]
  # Sort the genes from highest to lowest weight
  x <- x[order(x$mean.AUC, decreasing = TRUE), ]
  # Add gene and cluster id to the dataframe
  x$gene <- rownames(x)
  x$cluster <- i
  data.frame(x)
})
mgs_df <- do.call(rbind, mgs_fil)

idx <- split(seq(ncol(sce)), sce$cell_type_ord)
# downsample to at most 20 per identity & subset
# We are using 5 here to speed up the process but set to 75-100 for your real
# life analysis
n_cells <- 5
cs_keep <- lapply(idx, function(i) {
  n <- length(i)
  if (n < n_cells)
    n_cells <- n
  sample(i, n_cells)
})
sce <- sce[, unlist(cs_keep)]

res <- SPOTlight(
  x = sce,
  y = spe,
  groups = as.character(sce$cell_type_ord),
  mgs = mgs_df,
  hvg = hvg,
  weight_id = "mean.AUC",
  group_id = "cluster",
  gene_id = "gene")

**Comment by HelenaLC** [comment]
Could you please also print the sce and spe objects.

**Comment by MarcElosua** [comment]
This should be fixed in the latest release in bioconductor!
