### ISSUE TITLE
ST technology (the predecessor of 10X Visium technology)

### ISSUE THREAD

**Issue by wang0430** [MarcElosua/SPOTlight#90]
Hello, can spotlight support the data of ST technology (the predecessor of 10X Visium technology), and is there any corresponding operation document?

**Comment by HelenaLC** [comment]
Yes, the method should be applicable to both ST and Visium. The only difference is resolution/spot size and spot arrangement (hex vs grid)- but this doesn’t affect deconvolution w SPOTlight. There’s no supporting doc, but all is analogous given an appropriate single-cell reference.
