### ISSUE TITLE
plotSpatialScatterpie

### ISSUE THREAD

**Issue by wang0430** [MarcElosua/SPOTlight#92]
hi，
Error in plotSpatialScatterpie(sample, mat, cell_types = colnames(mat),  : 
  nrow(x) == nrow(y) is not TRUE
nrow(sample) is gene
nrow(mat) is celltype
I have drawn pictures like this before without any problems, but this time I reported an error.

**Comment by MarcElosua** [comment]
Could you provide a bit more information please?

**Comment by yutingdai1125** [comment]
I also have the error when run the function plotSpatialScatterpie( ).

**Comment by MarcElosua** [comment]
Hi @yutingdai1125 @wang0430 
Could you please provide a reproducible example following these [guidelines](https://stackoverflow.com/help/minimal-reproducible-example)  so that I can help you as efficiently as possible? Thank you!

**Comment by wang0430** [comment]
sample = readRDS("/data40T/wanggl/visium/VISDP000001/VISDS000001/process/Data/deco_sample.rds")
ct = colnames(mat)
mat[mat < 0.1] = 0
paletteMartin = c('#28CECA','#F38181','#4d638c','#87E293',
                  '#fcebb6','#25aff5','#F9CE00','#AC8F14',
                  '#000000','#63b931','#0066B3','#9c6644',
                  '#427aa1','#78c0a8','#e63f0a','#5e412f',
                  '#f07818','#791E94','#e09f3e','#ff5400')
pal = colorRampPalette(paletteMartin)(length(ct))
names(pal) = ct
p = plotSpatialScatterpie(sample,mat,
                          cell_types = colnames(mat),
                          img = TRUE,
                          scatterpie_alpha = 1,
                          pie_scale = 0.35) +
  scale_fill_manual(
    values = pal,
    breaks = names(pal))

Error in plotImage(x = img) : 
  is.matrix(x) | is.character(x) | is.array(x) | is(x, "rastergrob") |  .... is not TRUE

![1681871659738](https://user-images.githubusercontent.com/112233361/232951907-9e0de9ca-a902-4d61-996a-7f0de67ca0f2.png)
![1681871699918](https://user-images.githubusercontent.com/112233361/232951983-ad8d5985-d9d5-4507-aee3-996d0fbd1fe3.png)

**Comment by wang0430** [comment]
I found another error, 

Error in plotImage(x = img) : 
  is.matrix(x) | is.character(x) | is.array(x) | is(x, "rastergrob") |  .... is not TRUE
![1681881495441](https://user-images.githubusercontent.com/112233361/232973888-09cc2c98-9dbb-42e7-a1b1-3ba57be262e7.png)

**Comment by MarcElosua** [comment]
Hi,

Can you return `Seurat::Images(sample)`? Can you also try to pass `img = GetImage(sample, mode = "grob"))`?

It is a bit hard to help you debug without further information,

Thank you,
Marc

**Comment by wang0430** [comment]
I don't think I'm the only one who encounters this problem. This happens when I use other public datasets, and I have been successful with these public datasets before. Have you modified your code recently? Need me to upload the data to you?

![1681955097808](https://user-images.githubusercontent.com/112233361/233236549-046ea5ef-22e3-4a84-b717-36ae7d1831c3.png)
![1681955110213](https://user-images.githubusercontent.com/112233361/233236560-2b2ab787-3552-4d5c-a017-0c0ec45fabea.png)
![1681955136244](https://user-images.githubusercontent.com/112233361/233236570-5b92a001-14bb-43cb-84a1-9898cf603ba9.png)

**Comment by wang0430** [comment]
![1681958096400](https://user-images.githubusercontent.com/112233361/233242988-d01ba617-6cd7-411d-adfb-00dda2c47a2d.png)
I checked the source code and found that X (seurat object) was first converted into a matrix, and then x was required to be seurat, which caused me to keep making mistakes

**Comment by MarcElosua** [comment]
hi @wang0430 

Can you try  reinstalling SPOTlight from github? 

`devtools::install_github("https://github.com/MarcElosua/SPOTlight", ref = "main")`

I have fixed that issue but haven't updated the code on Bioconductor, thank you for the heads up!

Marc

**Comment by biobirds9** [comment]
> hi @wang0430
> 
> Can you try reinstalling SPOTlight from github?
> 
> `devtools::install_github("https://github.com/MarcElosua/SPOTlight", ref = "main")`
> 
> I have fixed that issue but haven't updated the code on Bioconductor, thank you for the heads up!
> 
> Marc

hi,
I have recently encountered the same problem and have reinstalled as you suggested, but still no solution. What can I do please?
