### ISSUE TITLE
assay %in% SeuratObject::Assays(x) is not TRUE

### ISSUE THREAD

**Issue by wang0430** [MarcElosua/SPOTlight#93]
I am performing SPOTlight and I am getting this error:
> res = SPOTlight(x = sce,y = sample, groups = sce$celltype, mgs = mgs_df, hvg = hvg, weight_id = "mean.AUC",
+                 group_id = "cluster", gene_id = "gene")
Error in .extract_counts(y, assay, slot) : 
  assay %in% SeuratObject::Assays(x) is not TRUE

**Comment by MarcElosua** [comment]
This is related to [issue 91](https://github.com/MarcElosua/SPOTlight/issues/91), could you please reply to the questions @HelenaLC asked so that we can help you address this? Thanks!
