### ISSUE TITLE
Q - Visium analysis - subset image and spot demultiplexing

### ISSUE THREAD

**Issue by cathalgking** [MarcElosua/SPOTlight#94]
I am analysing a 10x Visium dataset and I would like to examine 2 different areas or regions of the same Visium slide (image below). The data is from a mouse colon and some of the tissue is tumour and some is not. We would like to examine and compare the spots / genes in both regions (tumour vs non).
Can SPOTlight assist with this task? Can SPOTlight also de-multiplex Visium spots into its component cells?
Thanks

**Comment by MarcElosua** [comment]
Hi @cathalgking,

Thank you for your interest in SPOTlight. That looks like a very interesting analysis, SPOTlight can assist in decomposing the cell types for each spot as long as you have a single cell reference which contains a representation of the cells found on the tissue. Then you can compare cell type proportions between regions.

Hope this helps!
Marc

**Comment by cathalgking** [comment]
Thanks for your reply @MarcElosua. Can the reference be a reference from a public database (of the same tissue type)?
And in terms of the 2 regions on the tissue, what function or method can I use in SPOTlight to assign the 2 regions?

**Comment by MarcElosua** [comment]
The reference can be a public database, there is no problem there. However, you should check if the tumor cells are represented in the scRNAseq data. If not, the results should be interpreted accordingly - obtained proportions, in reality, could be lower in the tumor region if there is no tumor in the reference. 

For the "annotation" of the two regions I would recommend using manual annotation or a clustering approach to define the regions. SPOTlight doesn't incorporate those functionalities so I would recommend looking at these resources [OSTA](https://lmweber.org/OSTA-book/clustering.html) or [Seurat](https://satijalab.org/seurat/articles/spatial_vignette.html)

Hope this helps!

**Comment by cathalgking** [comment]
Ok, thanks for your replies. Can you show a simple example of how I would use spotlight to decompose cell types?

**Comment by MarcElosua** [comment]
Find a vignette with the steps [here](https://bioconductor.org/packages/release/bioc/vignettes/SPOTlight/inst/doc/SPOTlight_kidney.html)
