### ISSUE TITLE
In README.md the processed object can not find

### ISSUE THREAD

**Issue by Han117** [MarcElosua/SPOTlight#98]
In README.md

For the purpose of this tutorial we are going to use adult mouse brain data. The scRNAseq data can be downloaded [here](https://github.com/MarcElosua/SPOTlight/blob/v0.1.0), while the spatial data is the one put out publicly by [10X](https://www.10xgenomics.com/resources/datasets/) and the processed object can be downloaded [here](https://github.com/MarcElosua/SPOTlight/blob/v0.1.0/PENDING).

"the processed object can be downloaded [here]" can not find。

**Comment by MarcElosua** [comment]
Hi @Han117 

Please find the downsampled mouse brain data used for the vignette [here](https://github.com/MarcElosua/SPOTlight/blob/spotlight-0.1.7/sample_data/allen_cortex_dwn.rds)

**Comment by Han117** [comment]
Hi,@MarcElosua
Thank you very much for your answer. I found the processed object .

I want to ask about the dataset PBMC (GSE133549), which I downloaded from the GEO website, but these data sets have not been processed, there are no data types in these data sets, and the data sets are not in.rDS format.

 I saw that you used GSE133549 in your method, could you please provide the processed GSE133549 data set? Thank you very much.
